#include "fg_q38_math.h"
#include "fg_q38_schema.h"
#include "fg_ngram.h"
#include "fg_quant.h"
#include "fg_vk.h"

#include <fcntl.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

static fg_vk_context *context;
static fg_error error;

static fg_vk_tensor *tensor(const void *data,uint64_t bytes){fg_vk_tensor *result=NULL;if(fg_vk_tensor_create(context,bytes,&result,&error)!=FG_OK)return NULL;if(data&&fg_vk_tensor_write(result,0,data,bytes,&error)!=FG_OK){fg_vk_tensor_destroy(result);return NULL;}return result;}

static void make_q5_1_row(uint8_t *row,uint32_t values,uint32_t phase){
    for(uint32_t block=0;block<values/32u;block++){
        uint8_t *p=row+(uint64_t)block*24u;p[0]=0;p[1]=0x3c;p[2]=0;p[3]=0;uint32_t high=0;
        for(uint32_t i=0;i<32u;i++){uint32_t q=(i+block+phase)&31u;if(q&16u)high|=1u<<i;uint32_t j=i&15u;if(i<16u)p[8u+j]=(uint8_t)((p[8u+j]&0xf0u)|(q&15u));else p[8u+j]=(uint8_t)((p[8u+j]&0x0fu)|((q&15u)<<4u));}
        memcpy(p+4u,&high,4u);
    }
}

static int test_q8_dense(void){
    enum{INPUT=32,OUTPUT=8};float source[INPUT*OUTPUT],x[INPUT],got[OUTPUT];uint8_t quantized[FG_Q8_0_BLOCK_BYTES*OUTPUT];
    for(uint32_t i=0;i<INPUT;i++)x[i]=cosf((float)i*0.17f);
    for(uint32_t r=0;r<OUTPUT;r++){for(uint32_t i=0;i<INPUT;i++)source[r*INPUT+i]=sinf((float)(r*INPUT+i)*0.013f);fg_quantize_q8_0(source+r*INPUT,quantized+r*FG_Q8_0_BLOCK_BYTES,INPUT);}
    fg_vk_tensor *w=tensor(quantized,sizeof(quantized)),*input=tensor(x,sizeof(x)),*output=tensor(NULL,sizeof(got));int ok=w&&input&&output&&fg_vk_dense_q8_0_f32(context,output,w,input,INPUT,OUTPUT,1,1.0f,&error)==FG_OK&&fg_vk_tensor_read(output,0,got,sizeof(got),&error)==FG_OK;
    for(uint32_t r=0;ok&&r<OUTPUT;r++){const uint8_t *row=quantized+r*FG_Q8_0_BLOCK_BYTES;uint16_t half=(uint16_t)row[0]|(uint16_t)((uint16_t)row[1]<<8u);float ref=0.0f,d=fg_f16_to_f32(half);for(uint32_t i=0;i<INPUT;i++)ref=fmaf(d*(float)(int8_t)row[2u+i],x[i],ref);if(fabsf(got[r]-ref)>1e-4f*fmaxf(1.0f,fabsf(ref)))ok=0;}
    fg_vk_tensor_destroy(output);fg_vk_tensor_destroy(input);fg_vk_tensor_destroy(w);return ok;
}

static int test_q8_embedding(void){
    enum{ROWS=3,WIDTH=2560,COPIES=4};
    const uint64_t row_bytes=(uint64_t)(WIDTH/32u)*FG_Q8_0_BLOCK_BYTES;
    float *source=malloc((size_t)ROWS*WIDTH*sizeof(*source));
    float *expected=malloc(WIDTH*sizeof(*expected));
    float *got=malloc((size_t)COPIES*WIDTH*sizeof(*got));
    uint8_t *weights=malloc((size_t)ROWS*row_bytes);
    if(!source||!expected||!got||!weights){free(weights);free(got);free(expected);free(source);return 0;}
    for(uint32_t row=0;row<ROWS;row++)for(uint32_t i=0;i<WIDTH;i++)source[row*WIDTH+i]=sinf((float)(row*WIDTH+i)*0.0037f)*(float)(row+1u)+cosf((float)i*0.011f)*0.125f;
    for(uint32_t row=0;row<ROWS;row++)fg_quantize_q8_0(source+row*WIDTH,weights+(uint64_t)row*row_bytes,WIDTH);
    fg_dequantize_q8_0(weights+row_bytes,expected,WIDTH);
    uint32_t token_ids[ROWS]={2u,0u,1u};float *batch=malloc((size_t)ROWS*COPIES*WIDTH*4u);fg_vk_tensor *w=tensor(weights,(uint64_t)ROWS*row_bytes),*out=tensor(NULL,(uint64_t)COPIES*WIDTH*sizeof(*got)),*ids=tensor(token_ids,sizeof(token_ids)),*batch_out=tensor(NULL,(uint64_t)ROWS*COPIES*WIDTH*4u);
    int ok=batch&&w&&out&&ids&&batch_out&&fg_vk_embedding_q8_0(context,out,w,1u,WIDTH,ROWS,COPIES,&error)==FG_OK&&fg_vk_tensor_read(out,0,got,(uint64_t)COPIES*WIDTH*sizeof(*got),&error)==FG_OK&&fg_vk_embedding_q8_0_batch(context,batch_out,w,ids,ROWS,WIDTH,ROWS,COPIES,&error)==FG_OK&&fg_vk_tensor_read(batch_out,0,batch,(uint64_t)ROWS*COPIES*WIDTH*4u,&error)==FG_OK;
    for(uint32_t copy=0;ok&&copy<COPIES;copy++)for(uint32_t i=0;i<WIDTH;i++)if(got[copy*WIDTH+i]!=expected[i]){fprintf(stderr,"Q8 embedding copy %u element %u GPU=%g CPU=%g\n",copy,i,got[copy*WIDTH+i],expected[i]);ok=0;break;}
    for(uint32_t token=0;ok&&token<ROWS;token++){fg_dequantize_q8_0(weights+(uint64_t)token_ids[token]*row_bytes,expected,WIDTH);for(uint32_t copy=0;ok&&copy<COPIES;copy++)for(uint32_t i=0;i<WIDTH;i++)if(batch[((uint64_t)token*COPIES+copy)*WIDTH+i]!=expected[i]){fprintf(stderr,"batched Q8 embedding token %u copy %u element %u mismatch\n",token,copy,i);ok=0;break;}}
    fg_vk_tensor_destroy(batch_out);fg_vk_tensor_destroy(ids);fg_vk_tensor_destroy(out);fg_vk_tensor_destroy(w);free(batch);free(weights);free(got);free(expected);free(source);return ok;
}

static int test_hc_finalize(void){
    enum{HIDDEN=2560,GROUPS=4,HYPER=10240};
    float *normalized=malloc(HYPER*sizeof(*normalized)),*up=malloc(HYPER*sizeof(*up));
    float *expected=malloc(HIDDEN*sizeof(*expected)),*got=malloc(HIDDEN*sizeof(*got));
    if(!normalized||!up||!expected||!got){free(got);free(expected);free(up);free(normalized);return 0;}
    for(uint32_t group=0;group<GROUPS;group++)for(uint32_t i=0;i<HIDDEN;i++){uint32_t index=group*HIDDEN+i;normalized[index]=sinf((float)index*0.0019f);up[index]=cosf((float)index*0.0023f)*3.0f;}
    for(uint32_t i=0;i<HIDDEN;i++){expected[i]=0.0f;for(uint32_t group=0;group<GROUPS;group++){uint32_t index=group*HIDDEN+i;expected[i]+=normalized[index]/(1.0f+expf(-up[index]));}expected[i]/=(float)GROUPS;}
    fg_vk_tensor *n=tensor(normalized,HYPER*sizeof(*normalized)),*u=tensor(up,HYPER*sizeof(*up)),*o=tensor(NULL,HIDDEN*sizeof(*got));
    int ok=n&&u&&o&&fg_vk_hc_finalize(context,o,n,u,HIDDEN,GROUPS,1u,&error)==FG_OK&&fg_vk_tensor_read(o,0,got,HIDDEN*sizeof(*got),&error)==FG_OK;
    for(uint32_t i=0;ok&&i<HIDDEN;i++)if(fabsf(got[i]-expected[i])>2e-6f){fprintf(stderr,"final hyper-connection %u GPU=%g CPU=%g\n",i,got[i],expected[i]);ok=0;}
    fg_vk_tensor_destroy(o);fg_vk_tensor_destroy(u);fg_vk_tensor_destroy(n);free(got);free(expected);free(up);free(normalized);return ok;
}

static int test_q8_k_quant(void){float input[512];uint8_t cpu[2*FG_Q8_K_BLOCK_BYTES],gpu[sizeof(cpu)];for(uint32_t i=0;i<512u;i++)input[i]=sinf((float)i*0.031f)*3.0f+cosf((float)i*0.007f);fg_quantize_q8_k(input,cpu,512);fg_vk_tensor *x=tensor(input,sizeof(input)),*q=tensor(NULL,sizeof(gpu));int ok=x&&q&&fg_vk_quantize_q8_k(context,q,x,256,2,&error)==FG_OK&&fg_vk_tensor_read(q,0,gpu,sizeof(gpu),&error)==FG_OK;if(ok&&memcmp(cpu,gpu,sizeof(cpu))!=0){fprintf(stderr,"Q8_K GPU bytes differ from CPU oracle\n");ok=0;}fg_vk_tensor_destroy(q);fg_vk_tensor_destroy(x);return ok;}
static int test_q4_0_bytes(void){float input[32],got[32];uint8_t quantized[18];for(uint32_t i=0;i<16u;i++)input[i]=input[i+16u]=(float)((int32_t)i-8);fg_quantize_q4_0(input,quantized,32);int ok=quantized[0]==0x00u&&quantized[1]==0x3cu;for(uint32_t i=0;ok&&i<16u;i++)if(quantized[2u+i]!=(uint8_t)(i|(i<<4u)))ok=0;fg_dequantize_q4_0(quantized,got,32);for(uint32_t i=0;ok&&i<32u;i++)if(got[i]!=input[i])ok=0;return ok;}
static uint16_t to_bf16(float value){uint32_t bits;memcpy(&bits,&value,4u);return(uint16_t)(bits>>16u);}
static float from_bf16(uint16_t value){uint32_t bits=(uint32_t)value<<16u;float result;memcpy(&result,&bits,4u);return result;}
static int test_qsa_quant_and_bf16(void){
    enum{WIDTH=512,OUTPUT=7};float input[WIDTH],deq_cpu[WIDTH],deq_gpu[WIDTH],expected[OUTPUT],got[OUTPUT];uint8_t q8_cpu[(WIDTH/32)*34],q8_gpu[sizeof(q8_cpu)],q4_cpu[(WIDTH/32)*18],q4_gpu[sizeof(q4_cpu)];for(uint32_t i=0;i<WIDTH;i++)input[i]=sinf((float)i*0.023f)*4.0f+cosf((float)i*0.071f)*0.25f;fg_quantize_q8_0(input,q8_cpu,WIDTH);fg_quantize_q4_0(input,q4_cpu,WIDTH);fg_vk_tensor *x=tensor(input,sizeof(input)),*q8=tensor(NULL,sizeof(q8_gpu)),*q4=tensor(NULL,sizeof(q4_gpu));int ok=x&&q8&&q4&&fg_vk_quantize_q8_0(context,q8,x,WIDTH,1,&error)==FG_OK&&fg_vk_quantize_q4_0(context,q4,x,WIDTH,1,&error)==FG_OK&&fg_vk_tensor_read(q8,0,q8_gpu,sizeof(q8_gpu),&error)==FG_OK&&fg_vk_tensor_read(q4,0,q4_gpu,sizeof(q4_gpu),&error)==FG_OK;
    /* Compare dequantized values rather than raw bytes — real GPU float
       rounding (e.g. RADV GFX1013) may produce a different scale factor
       while the dequantized result stays within one quantization step. */
    fg_dequantize_q8_0(q8_cpu,deq_cpu,WIDTH);fg_dequantize_q8_0(q8_gpu,deq_gpu,WIDTH);for(uint32_t i=0;ok&&i<WIDTH;i++)if(fabsf(deq_cpu[i]-deq_gpu[i])>0.05f*fmaxf(1.0f,fabsf(input[i]))){fprintf(stderr,"Q8_0 GPU dequant %u CPU=%g GPU=%g input=%g\n",i,deq_cpu[i],deq_gpu[i],input[i]);ok=0;}
    fg_dequantize_q4_0(q4_cpu,deq_cpu,WIDTH);fg_dequantize_q4_0(q4_gpu,deq_gpu,WIDTH);for(uint32_t i=0;ok&&i<WIDTH;i++)if(fabsf(deq_cpu[i]-deq_gpu[i])>0.25f*fmaxf(1.0f,fabsf(input[i]))){fprintf(stderr,"Q4_0 GPU dequant %u CPU=%g GPU=%g input=%g\n",i,deq_cpu[i],deq_gpu[i],input[i]);ok=0;}
    for(uint32_t i=0;ok&&i<WIDTH;i++)if(!isfinite(deq_gpu[i]))ok=0;
    uint16_t weights[WIDTH*OUTPUT];for(uint32_t row=0;row<OUTPUT;row++){expected[row]=0.0f;for(uint32_t i=0;i<WIDTH;i++){weights[row*WIDTH+i]=to_bf16(cosf((float)(row*WIDTH+i)*0.0031f));expected[row]=fmaf(from_bf16(weights[row*WIDTH+i]),input[i],expected[row]);}}fg_vk_tensor *w=tensor(weights,sizeof(weights)),*o=tensor(NULL,sizeof(got));ok=ok&&w&&o&&fg_vk_dense_bf16_f32(context,o,w,x,WIDTH,OUTPUT,1,&error)==FG_OK&&fg_vk_tensor_read(o,0,got,sizeof(got),&error)==FG_OK;for(uint32_t row=0;ok&&row<OUTPUT;row++)if(fabsf(got[row]-expected[row])>3e-4f*fmaxf(1.0f,fabsf(expected[row]))){fprintf(stderr,"BF16 dense row %u GPU=%g CPU=%g\n",row,got[row],expected[row]);ok=0;}fg_vk_tensor_destroy(o);fg_vk_tensor_destroy(w);fg_vk_tensor_destroy(q4);fg_vk_tensor_destroy(q8);fg_vk_tensor_destroy(x);return ok;
}

typedef struct score_id {float score;uint32_t id;} score_id;
static int test_qsa_record_commit(void){
    enum{SLOTS=2,TOKENS=3,KEY=512,INDEX=128};float key[KEY],value[KEY],index_key[INDEX];uint32_t position[3]={31u,37u,41u};uint8_t expected[FG_Q38_QSA_TOKEN_RECORD_BYTES],got[sizeof(expected)],history[FG_Q38_QSA_INDEX_KEY_BYTES];for(uint32_t i=0;i<KEY;i++){key[i]=sinf((float)i*0.013f);value[i]=cosf((float)i*0.017f)*2.0f;}for(uint32_t i=0;i<INDEX;i++)index_key[i]=sinf((float)i*0.029f)-0.25f;memset(expected,0,sizeof(expected));
    fg_vk_tensor *gkey=tensor(key,sizeof(key)),*gvalue=tensor(value,sizeof(value)),*gindex=tensor(index_key,sizeof(index_key)),*gposition=tensor(position,sizeof(position)),*qkey=tensor(NULL,FG_Q38_QSA_KEY_BYTES),*qvalue=tensor(NULL,FG_Q38_QSA_VALUE_BYTES),*qindex=tensor(NULL,FG_Q38_QSA_INDEX_KEY_BYTES),*records=tensor(NULL,(uint64_t)SLOTS*TOKENS*FG_Q38_QSA_TOKEN_RECORD_BYTES),*index_history=tensor(NULL,(uint64_t)SLOTS*TOKENS*FG_Q38_QSA_INDEX_KEY_BYTES);int ok=gkey&&gvalue&&gindex&&gposition&&qkey&&qvalue&&qindex&&records&&index_history;if(ok){memset(fg_vk_tensor_map(records),0,(size_t)fg_vk_tensor_bytes(records));memset(fg_vk_tensor_map(index_history),0,(size_t)fg_vk_tensor_bytes(index_history));ok=fg_vk_begin(context,&error)==FG_OK&&fg_vk_quantize_q8_0(context,qkey,gkey,KEY,1u,&error)==FG_OK&&fg_vk_quantize_q8_0(context,qvalue,gvalue,KEY,1u,&error)==FG_OK&&fg_vk_quantize_q8_0(context,qindex,gindex,INDEX,1u,&error)==FG_OK&&fg_vk_qsa_record_commit(context,records,index_history,qkey,qvalue,qindex,gposition,1u,2u,TOKENS,&error)==FG_OK;}if(ok){const uint8_t *pending=(const uint8_t *)fg_vk_tensor_map(records)+(1u*TOKENS+2u)*FG_Q38_QSA_TOKEN_RECORD_BYTES;for(uint32_t i=0;i<FG_Q38_QSA_TOKEN_RECORD_BYTES;i++)if(pending[i]!=0u){ok=0;break;}}if(ok)ok=fg_vk_end(context,&error)==FG_OK;if(ok)ok=fg_vk_tensor_read(qkey,0,expected,FG_Q38_QSA_KEY_BYTES,&error)==FG_OK&&fg_vk_tensor_read(qvalue,0,expected+FG_Q38_QSA_KEY_BYTES,FG_Q38_QSA_VALUE_BYTES,&error)==FG_OK&&fg_vk_tensor_read(qindex,0,expected+FG_Q38_QSA_KEY_BYTES+FG_Q38_QSA_VALUE_BYTES,FG_Q38_QSA_INDEX_KEY_BYTES,&error)==FG_OK;if(ok){memcpy(expected+FG_Q38_QSA_KEY_BYTES+FG_Q38_QSA_VALUE_BYTES+FG_Q38_QSA_INDEX_KEY_BYTES,position,sizeof(position));ok=fg_vk_tensor_read(records,(uint64_t)(1u*TOKENS+2u)*FG_Q38_QSA_TOKEN_RECORD_BYTES,got,sizeof(got),&error)==FG_OK&&fg_vk_tensor_read(index_history,(uint64_t)(1u*TOKENS+2u)*FG_Q38_QSA_INDEX_KEY_BYTES,history,sizeof(history),&error)==FG_OK&&memcmp(got,expected,sizeof(got))==0&&memcmp(history,expected+FG_Q38_QSA_KEY_BYTES+FG_Q38_QSA_VALUE_BYTES,sizeof(history))==0;}else if(fg_vk_batch_active(context))fg_vk_end(context,&error);for(uint32_t slot=0;ok&&slot<SLOTS;slot++)for(uint32_t token_id=0;token_id<TOKENS;token_id++)if(slot!=1u||token_id!=2u){const uint8_t *record=(const uint8_t *)fg_vk_tensor_map(records)+(slot*TOKENS+token_id)*FG_Q38_QSA_TOKEN_RECORD_BYTES;for(uint32_t i=0;i<FG_Q38_QSA_TOKEN_RECORD_BYTES;i++)if(record[i]!=0u){ok=0;break;}}fg_vk_tensor_destroy(index_history);fg_vk_tensor_destroy(records);fg_vk_tensor_destroy(qindex);fg_vk_tensor_destroy(qvalue);fg_vk_tensor_destroy(qkey);fg_vk_tensor_destroy(gposition);fg_vk_tensor_destroy(gindex);fg_vk_tensor_destroy(gvalue);fg_vk_tensor_destroy(gkey);return ok;
}

static int test_qsa_record_gather(void){
    enum{CAPACITY=10,BLOCKS=2,TAIL=2,SELECTED=BLOCKS*4+TAIL};uint8_t *records=malloc((size_t)CAPACITY*FG_Q38_QSA_TOKEN_RECORD_BYTES),*got=malloc((size_t)SELECTED*FG_Q38_QSA_TOKEN_RECORD_BYTES);uint32_t ids[BLOCKS]={1u,0u};if(!records||!got){free(got);free(records);return 0;}for(uint32_t token=0;token<CAPACITY;token++)memset(records+(uint64_t)token*FG_Q38_QSA_TOKEN_RECORD_BYTES,(int)(token+1u),FG_Q38_QSA_TOKEN_RECORD_BYTES);fg_vk_tensor *source=tensor(records,(uint64_t)CAPACITY*FG_Q38_QSA_TOKEN_RECORD_BYTES),*block_ids=tensor(ids,sizeof(ids)),*output=tensor(NULL,(uint64_t)SELECTED*FG_Q38_QSA_TOKEN_RECORD_BYTES);int ok=source&&block_ids&&output&&fg_vk_qsa_record_gather(context,output,source,block_ids,0u,CAPACITY,BLOCKS,8u,TAIL,&error)==FG_OK&&fg_vk_tensor_read(output,0,got,(uint64_t)SELECTED*FG_Q38_QSA_TOKEN_RECORD_BYTES,&error)==FG_OK;const uint32_t expected[SELECTED]={4u,5u,6u,7u,0u,1u,2u,3u,8u,9u};for(uint32_t i=0;ok&&i<SELECTED;i++)for(uint32_t byte=0;byte<FG_Q38_QSA_TOKEN_RECORD_BYTES;byte++)if(got[(uint64_t)i*FG_Q38_QSA_TOKEN_RECORD_BYTES+byte]!=(uint8_t)(expected[i]+1u)){ok=0;break;}fg_vk_tensor_destroy(output);fg_vk_tensor_destroy(block_ids);fg_vk_tensor_destroy(source);free(got);free(records);return ok;
}

static int score_id_compare(const void *a,const void *b){const score_id *x=a,*y=b;if(x->score>y->score)return -1;if(x->score<y->score)return 1;return x->id<y->id?-1:x->id>y->id;}
static int test_qsa_indexer(void){
    enum{TOKENS=13,BLOCKS=3};float projected[512],query[512],qnorm[128],knorm[128],raw[TOKENS*128],dequant[TOKENS*128];uint8_t quant[TOKENS*136];uint32_t positions[TOKENS*3];for(uint32_t i=0;i<512u;i++)projected[i]=sinf((float)(i+3u)*0.019f)+0.2f*cosf((float)i*0.007f);memcpy(query,projected,sizeof(query));for(uint32_t i=0;i<128u;i++){qnorm[i]=0.03f*sinf((float)i*0.051f);knorm[i]=0.04f*cosf((float)i*0.037f);}for(uint32_t token_id=0;token_id<TOKENS;token_id++){for(uint32_t axis=0;axis<3u;axis++)positions[axis*TOKENS+token_id]=token_id;for(uint32_t i=0;i<128u;i++)raw[token_id*128u+i]=sinf((float)(token_id+1u)*(float)(i+1u)*0.0017f)+0.15f*cosf((float)(token_id+2u)*(float)(i+3u)*0.0009f);fg_quantize_q8_0(raw+token_id*128u,quant+token_id*136u,128u);fg_dequantize_q8_0(quant+token_id*136u,dequant+token_id*128u,128u);}uint32_t current[3]={TOKENS-1,TOKENS-1,TOKENS-1};int ok=fg_q38_rms_mrope(query,4u,128u,qnorm,current,&error)==FG_OK;uint32_t expected_tokens[TOKENS],expected_count=0;ok=ok&&fg_q38_qsa_index_select_reference(projected,dequant,TOKENS,qnorm,knorm,expected_tokens,TOKENS,&expected_count,&error)==FG_OK;
    uint32_t interleaved_positions[TOKENS*3];for(uint32_t token_id=0;token_id<TOKENS;token_id++)for(uint32_t axis=0;axis<3u;axis++)interleaved_positions[token_id*3u+axis]=positions[axis*TOKENS+token_id];
    fg_vk_tensor *gq=tensor(query,sizeof(query)),*gk=tensor(quant,sizeof(quant)),*gn=tensor(knorm,sizeof(knorm)),*gp=tensor(interleaved_positions,sizeof(interleaved_positions)),*gs=tensor(NULL,BLOCKS*4u),*gi=tensor(NULL,BLOCKS*4u),*gos=tensor(NULL,BLOCKS*4u),*goi=tensor(NULL,BLOCKS*4u);uint32_t produced=0,ids[BLOCKS];ok=ok&&gq&&gk&&gn&&gp&&gs&&gi&&gos&&goi&&fg_vk_qsa_index_score(context,gs,gi,gq,gk,gn,gp,TOKENS,&error)==FG_OK&&fg_vk_topk_reduce(context,gos,goi,gs,gi,BLOCKS,&produced,&error)==FG_OK&&produced==BLOCKS&&fg_vk_tensor_read(goi,0,ids,sizeof(ids),&error)==FG_OK;for(uint32_t i=0;ok&&i<BLOCKS;i++)if(ids[i]!=expected_tokens[i*4u]/4u)ok=0;fg_vk_tensor_destroy(goi);fg_vk_tensor_destroy(gos);fg_vk_tensor_destroy(gi);fg_vk_tensor_destroy(gs);fg_vk_tensor_destroy(gp);fg_vk_tensor_destroy(gn);fg_vk_tensor_destroy(gk);fg_vk_tensor_destroy(gq);
    enum{COUNT=5000};score_id *reference=malloc(COUNT*sizeof(*reference));float *scores=malloc(COUNT*4u);uint32_t *input_ids=malloc(COUNT*4u),top_ids[512];if(!reference||!scores||!input_ids)ok=0;for(uint32_t i=0;ok&&i<COUNT;i++){scores[i]=sinf((float)i*0.013f)+(float)i*1e-7f;input_ids[i]=i;reference[i]=(score_id){scores[i],i};}if(ok)qsort(reference,COUNT,sizeof(*reference),score_id_compare);fg_vk_tensor *a_s=ok?tensor(scores,COUNT*4u):NULL,*a_i=ok?tensor(input_ids,COUNT*4u):NULL,*b_s=ok?tensor(NULL,1024u*4u):NULL,*b_i=ok?tensor(NULL,1024u*4u):NULL,*c_s=ok?tensor(NULL,512u*4u):NULL,*c_i=ok?tensor(NULL,512u*4u):NULL;uint32_t mid=0,final=0;ok=ok&&a_s&&a_i&&b_s&&b_i&&c_s&&c_i&&fg_vk_topk_reduce(context,b_s,b_i,a_s,a_i,COUNT,&mid,&error)==FG_OK&&mid==1024u&&fg_vk_topk_reduce(context,c_s,c_i,b_s,b_i,mid,&final,&error)==FG_OK&&final==512u&&fg_vk_tensor_read(c_i,0,top_ids,sizeof(top_ids),&error)==FG_OK;for(uint32_t i=0;ok&&i<512u;i++)if(top_ids[i]!=reference[i].id){fprintf(stderr,"top-k mismatch %u GPU=%u CPU=%u\n",i,top_ids[i],reference[i].id);ok=0;}fg_vk_tensor_destroy(c_i);fg_vk_tensor_destroy(c_s);fg_vk_tensor_destroy(b_i);fg_vk_tensor_destroy(b_s);fg_vk_tensor_destroy(a_i);fg_vk_tensor_destroy(a_s);free(input_ids);free(scores);free(reference);return ok;
}

static int test_output_topk(void){
    enum{COUNT=FG_Q38_VOCAB_SIZE,FIRST=(COUNT+4095)/4096*512};float *scores=malloc((size_t)COUNT*4u),top_scores[4];uint32_t *ids=malloc((size_t)COUNT*4u),top_ids[4];if(!scores||!ids){free(ids);free(scores);return 0;}for(uint32_t i=0;i<COUNT;i++){scores[i]=-(float)i;ids[i]=i;}scores[12345]=100.0f;scores[23456]=99.0f;scores[34567]=98.0f;scores[45678]=NAN;fg_vk_tensor *input_scores=tensor(scores,(uint64_t)COUNT*4u),*input_ids=tensor(ids,(uint64_t)COUNT*4u),*scratch_scores[2]={tensor(NULL,(uint64_t)FIRST*4u),tensor(NULL,(uint64_t)FIRST*4u)},*scratch_ids[2]={tensor(NULL,(uint64_t)FIRST*4u),tensor(NULL,(uint64_t)FIRST*4u)};uint32_t count=COUNT,slot=0;int ok=input_scores&&input_ids&&scratch_scores[0]&&scratch_scores[1]&&scratch_ids[0]&&scratch_ids[1]&&fg_vk_begin(context,&error)==FG_OK;const fg_vk_tensor *source_scores=input_scores,*source_ids=input_ids;while(ok&&count>512u){uint32_t next=0;ok=fg_vk_topk_reduce(context,scratch_scores[slot],scratch_ids[slot],source_scores,source_ids,count,&next,&error)==FG_OK;source_scores=scratch_scores[slot];source_ids=scratch_ids[slot];count=next;slot^=1u;}if(ok)ok=fg_vk_end(context,&error)==FG_OK&&count==512u&&fg_vk_tensor_read(source_scores,0,top_scores,sizeof(top_scores),&error)==FG_OK&&fg_vk_tensor_read(source_ids,0,top_ids,sizeof(top_ids),&error)==FG_OK&&top_ids[0]==45678u&&!isfinite(top_scores[0])&&top_ids[1]==12345u&&top_ids[2]==23456u&&top_ids[3]==34567u&&top_scores[1]==100.0f&&top_scores[2]==99.0f&&top_scores[3]==98.0f;else if(fg_vk_batch_active(context))fg_vk_end(context,&error);fg_vk_tensor_destroy(scratch_ids[1]);fg_vk_tensor_destroy(scratch_ids[0]);fg_vk_tensor_destroy(scratch_scores[1]);fg_vk_tensor_destroy(scratch_scores[0]);fg_vk_tensor_destroy(input_ids);fg_vk_tensor_destroy(input_scores);free(ids);free(scores);return ok;
}

static int test_qsa_prefill_prepare(void){
    enum{TOKENS=3,QG=12288,Q=6144,K=512,IQ=512};float *raw_qg=malloc((size_t)TOKENS*QG*4u),*raw_k=malloc((size_t)TOKENS*K*4u),*raw_iq=malloc((size_t)TOKENS*IQ*4u),*batch_q=malloc((size_t)TOKENS*Q*4u),*batch_gate=malloc((size_t)TOKENS*Q*4u),*batch_k=malloc((size_t)TOKENS*K*4u),*batch_iq=malloc((size_t)TOKENS*IQ*4u);float qnorm[256],knorm[256],inorm[128];uint32_t positions[TOKENS*3u];if(!raw_qg||!raw_k||!raw_iq||!batch_q||!batch_gate||!batch_k||!batch_iq){free(batch_iq);free(batch_k);free(batch_gate);free(batch_q);free(raw_iq);free(raw_k);free(raw_qg);return 0;}for(uint32_t token=0;token<TOKENS;token++){positions[token*3u]=17u+token;positions[token*3u+1u]=5u+token*2u;positions[token*3u+2u]=9u+token*3u;for(uint32_t i=0;i<QG;i++)raw_qg[(uint64_t)token*QG+i]=sinf((float)(token+1u)*(float)(i+3u)*0.0013f)+0.07f*cosf((float)i*0.0047f);for(uint32_t i=0;i<K;i++)raw_k[(uint64_t)token*K+i]=cosf((float)(token+2u)*(float)(i+1u)*0.0021f);for(uint32_t i=0;i<IQ;i++)raw_iq[(uint64_t)token*IQ+i]=sinf((float)(token+3u)*(float)(i+2u)*0.0019f);}for(uint32_t i=0;i<256u;i++){qnorm[i]=0.02f*sinf((float)i*0.017f);knorm[i]=0.03f*cosf((float)i*0.013f);}for(uint32_t i=0;i<128u;i++)inorm[i]=0.025f*sinf((float)i*0.023f);
    fg_vk_tensor *rq=tensor(raw_qg,(uint64_t)TOKENS*QG*4u),*rk=tensor(raw_k,(uint64_t)TOKENS*K*4u),*ri=tensor(raw_iq,(uint64_t)TOKENS*IQ*4u),*qn=tensor(qnorm,sizeof(qnorm)),*kn=tensor(knorm,sizeof(knorm)),*in=tensor(inorm,sizeof(inorm)),*pos=tensor(positions,sizeof(positions)),*bq=tensor(NULL,(uint64_t)TOKENS*Q*4u),*bg=tensor(NULL,(uint64_t)TOKENS*Q*4u),*bk=tensor(NULL,(uint64_t)TOKENS*K*4u),*bi=tensor(NULL,(uint64_t)TOKENS*IQ*4u);int ok=rq&&rk&&ri&&qn&&kn&&in&&pos&&bq&&bg&&bk&&bi&&fg_vk_qsa_prepare_prefill(context,bq,bg,bk,rq,rk,qn,kn,pos,TOKENS,&error)==FG_OK&&fg_vk_qsa_index_prepare_prefill(context,bi,ri,in,pos,TOKENS,&error)==FG_OK&&fg_vk_tensor_read(bq,0,batch_q,(uint64_t)TOKENS*Q*4u,&error)==FG_OK&&fg_vk_tensor_read(bg,0,batch_gate,(uint64_t)TOKENS*Q*4u,&error)==FG_OK&&fg_vk_tensor_read(bk,0,batch_k,(uint64_t)TOKENS*K*4u,&error)==FG_OK&&fg_vk_tensor_read(bi,0,batch_iq,(uint64_t)TOKENS*IQ*4u,&error)==FG_OK;
    for(uint32_t token=0;ok&&token<TOKENS;token++){fg_vk_tensor *rqv=NULL,*rkv=NULL,*riv=NULL,*pv=NULL,*sq=tensor(NULL,Q*4u),*sg=tensor(NULL,Q*4u),*sk=tensor(NULL,K*4u),*si=tensor(NULL,IQ*4u);float *single_q=malloc(Q*4u),*single_gate=malloc(Q*4u);float single_k[K],single_iq[IQ];ok=sq&&sg&&sk&&si&&single_q&&single_gate&&fg_vk_tensor_view(rq,(uint64_t)token*QG*4u,QG*4u,&rqv,&error)==FG_OK&&fg_vk_tensor_view(rk,(uint64_t)token*K*4u,K*4u,&rkv,&error)==FG_OK&&fg_vk_tensor_view(ri,(uint64_t)token*IQ*4u,IQ*4u,&riv,&error)==FG_OK&&fg_vk_tensor_view(pos,(uint64_t)token*3u*4u,3u*4u,&pv,&error)==FG_OK&&fg_vk_qsa_prepare(context,sq,sg,sk,rqv,rkv,qn,kn,pv,&error)==FG_OK&&fg_vk_qsa_index_prepare(context,si,riv,in,pv,&error)==FG_OK&&fg_vk_tensor_read(sq,0,single_q,Q*4u,&error)==FG_OK&&fg_vk_tensor_read(sg,0,single_gate,Q*4u,&error)==FG_OK&&fg_vk_tensor_read(sk,0,single_k,K*4u,&error)==FG_OK&&fg_vk_tensor_read(si,0,single_iq,IQ*4u,&error)==FG_OK;for(uint32_t i=0;ok&&i<Q;i++)if(fabsf(batch_q[(uint64_t)token*Q+i]-single_q[i])>4e-5f||batch_gate[(uint64_t)token*Q+i]!=single_gate[i])ok=0;for(uint32_t i=0;ok&&i<K;i++)if(fabsf(batch_k[(uint64_t)token*K+i]-single_k[i])>4e-5f||fabsf(batch_iq[(uint64_t)token*IQ+i]-single_iq[i])>4e-5f)ok=0;free(single_gate);free(single_q);fg_vk_tensor_destroy(si);fg_vk_tensor_destroy(sk);fg_vk_tensor_destroy(sg);fg_vk_tensor_destroy(sq);fg_vk_tensor_destroy(pv);fg_vk_tensor_destroy(riv);fg_vk_tensor_destroy(rkv);fg_vk_tensor_destroy(rqv);}
    fg_vk_tensor_destroy(bi);fg_vk_tensor_destroy(bk);fg_vk_tensor_destroy(bg);fg_vk_tensor_destroy(bq);fg_vk_tensor_destroy(pos);fg_vk_tensor_destroy(in);fg_vk_tensor_destroy(kn);fg_vk_tensor_destroy(qn);fg_vk_tensor_destroy(ri);fg_vk_tensor_destroy(rk);fg_vk_tensor_destroy(rq);free(batch_iq);free(batch_k);free(batch_gate);free(batch_q);free(raw_iq);free(raw_k);free(raw_qg);return ok;
}

static int test_qsa_attention(void){
    enum{QG=12288,Q=6144,K=512,SELECTED=17};float *raw_qg=malloc(QG*4u),raw_k[K],qnorm[256],knorm[256],expected_q[Q],expected_gate[Q],expected_k[K],got_q[Q],got_gate[Q],got_k[K],raw_iq[512],inorm[128],expected_iq[512],got_iq[512];if(!raw_qg)return 0;for(uint32_t i=0;i<QG;i++)raw_qg[i]=sinf((float)i*0.0041f)+0.1f*cosf((float)i*0.013f);for(uint32_t i=0;i<K;i++)raw_k[i]=cosf((float)i*0.009f)-0.05f*sinf((float)i*0.021f);for(uint32_t i=0;i<256u;i++){qnorm[i]=0.03f*sinf((float)i*0.017f);knorm[i]=0.02f*cosf((float)i*0.023f);}uint32_t position[3]={19,7,11};for(uint32_t head=0;head<24u;head++){for(uint32_t i=0;i<256u;i++){expected_q[head*256u+i]=raw_qg[head*512u+i];expected_gate[head*256u+i]=raw_qg[head*512u+256u+i];}if(fg_q38_rms_mrope(expected_q+head*256u,1u,256u,qnorm,position,&error)!=FG_OK){free(raw_qg);return 0;}}memcpy(expected_k,raw_k,sizeof(raw_k));for(uint32_t head=0;head<2u;head++)if(fg_q38_rms_mrope(expected_k+head*256u,1u,256u,knorm,position,&error)!=FG_OK){free(raw_qg);return 0;}for(uint32_t i=0;i<512u;i++)raw_iq[i]=sinf((float)i*0.012f);for(uint32_t i=0;i<128u;i++)inorm[i]=0.04f*cosf((float)i*0.031f);memcpy(expected_iq,raw_iq,sizeof(raw_iq));if(fg_q38_rms_mrope(expected_iq,4u,128u,inorm,position,&error)!=FG_OK){free(raw_qg);return 0;}
    fg_vk_tensor *grq=tensor(raw_qg,QG*4u),*grk=tensor(raw_k,sizeof(raw_k)),*gqn=tensor(qnorm,sizeof(qnorm)),*gkn=tensor(knorm,sizeof(knorm)),*gpos=tensor(position,sizeof(position)),*gq=tensor(NULL,Q*4u),*gg=tensor(NULL,Q*4u),*gk=tensor(NULL,K*4u),*griq=tensor(raw_iq,sizeof(raw_iq)),*gin=tensor(inorm,sizeof(inorm)),*giq=tensor(NULL,sizeof(got_iq));int ok=grq&&grk&&gqn&&gkn&&gpos&&gq&&gg&&gk&&griq&&gin&&giq&&fg_vk_qsa_prepare(context,gq,gg,gk,grq,grk,gqn,gkn,gpos,&error)==FG_OK&&fg_vk_qsa_index_prepare(context,giq,griq,gin,gpos,&error)==FG_OK&&fg_vk_tensor_read(gq,0,got_q,sizeof(got_q),&error)==FG_OK&&fg_vk_tensor_read(gg,0,got_gate,sizeof(got_gate),&error)==FG_OK&&fg_vk_tensor_read(gk,0,got_k,sizeof(got_k),&error)==FG_OK&&fg_vk_tensor_read(giq,0,got_iq,sizeof(got_iq),&error)==FG_OK;for(uint32_t i=0;ok&&i<Q;i++)if(fabsf(got_q[i]-expected_q[i])>4e-5f||got_gate[i]!=expected_gate[i])ok=0;for(uint32_t i=0;ok&&i<K;i++)if(fabsf(got_k[i]-expected_k[i])>4e-5f||fabsf(got_iq[i]-expected_iq[i])>4e-5f)ok=0;
    uint8_t *records=calloc(SELECTED,FG_Q38_QSA_TOKEN_RECORD_BYTES);float *decoded_keys=malloc(SELECTED*K*4u),*decoded_values=malloc(SELECTED*K*4u),*cpu=malloc(Q*4u),*gpu=malloc(Q*4u);if(!records||!decoded_keys||!decoded_values||!cpu||!gpu)ok=0;for(uint32_t token_id=0;ok&&token_id<SELECTED;token_id++){float key[K],value[K];uint8_t *record=records+(uint64_t)token_id*FG_Q38_QSA_TOKEN_RECORD_BYTES;for(uint32_t i=0;i<K;i++){key[i]=sinf((float)(token_id+1u)*(float)(i+2u)*0.0023f);value[i]=cosf((float)(token_id+3u)*(float)(i+1u)*0.0017f)*2.0f;}fg_quantize_q8_0(key,record,K);fg_quantize_q8_0(value,record+FG_Q38_QSA_KEY_BYTES,K);fg_dequantize_q8_0(record,decoded_keys+token_id*K,K);fg_dequantize_q8_0(record+FG_Q38_QSA_KEY_BYTES,decoded_values+token_id*K,K);}
    for(uint32_t head=0;ok&&head<24u;head++){uint32_t kv=head/12u;float scores[SELECTED],maximum=-INFINITY,denom=0.0f;for(uint32_t token_id=0;token_id<SELECTED;token_id++){float dot=0.0f;for(uint32_t i=0;i<256u;i++)dot=fmaf(expected_q[head*256u+i],decoded_keys[token_id*K+kv*256u+i],dot);scores[token_id]=dot*0.0625f;maximum=fmaxf(maximum,scores[token_id]);}for(uint32_t token_id=0;token_id<SELECTED;token_id++)denom+=expf(scores[token_id]-maximum);for(uint32_t i=0;i<256u;i++){float sum=0.0f;for(uint32_t token_id=0;token_id<SELECTED;token_id++)sum=fmaf(expf(scores[token_id]-maximum),decoded_values[token_id*K+kv*256u+i],sum);cpu[head*256u+i]=sum/denom/(1.0f+expf(-expected_gate[head*256u+i]));}}
    fg_vk_tensor *grecord=ok?tensor(records,SELECTED*FG_Q38_QSA_TOKEN_RECORD_BYTES):NULL,*gout=ok?tensor(NULL,Q*4u):NULL;ok=ok&&grecord&&gout&&fg_vk_qsa_attention(context,gout,grecord,gq,gg,SELECTED,&error)==FG_OK&&fg_vk_tensor_read(gout,0,gpu,Q*4u,&error)==FG_OK;for(uint32_t i=0;ok&&i<Q;i++)if(fabsf(gpu[i]-cpu[i])>4e-4f*fmaxf(1.0f,fabsf(cpu[i]))){fprintf(stderr,"QSA attention %u GPU=%g CPU=%g\n",i,gpu[i],cpu[i]);ok=0;}fg_vk_tensor_destroy(gout);fg_vk_tensor_destroy(grecord);free(gpu);free(cpu);free(decoded_values);free(decoded_keys);free(records);fg_vk_tensor_destroy(giq);fg_vk_tensor_destroy(gin);fg_vk_tensor_destroy(griq);fg_vk_tensor_destroy(gk);fg_vk_tensor_destroy(gg);fg_vk_tensor_destroy(gq);fg_vk_tensor_destroy(gpos);fg_vk_tensor_destroy(gkn);fg_vk_tensor_destroy(gqn);fg_vk_tensor_destroy(grk);fg_vk_tensor_destroy(grq);free(raw_qg);return ok;
}

static int test_qsa_attention_single(void){float query[6144]={0},gate[6144]={0},key[512]={0},value[512],decoded[512],got[6144];uint8_t record[FG_Q38_QSA_TOKEN_RECORD_BYTES]={0};for(uint32_t i=0;i<512u;i++)value[i]=cosf((float)i*0.017f)*2.0f;fg_quantize_q8_0(key,record,512u);fg_quantize_q8_0(value,record+FG_Q38_QSA_KEY_BYTES,512u);fg_dequantize_q8_0(record+FG_Q38_QSA_KEY_BYTES,decoded,512u);fg_vk_tensor *r=tensor(record,sizeof(record)),*q=tensor(query,sizeof(query)),*g=tensor(gate,sizeof(gate)),*o=tensor(NULL,sizeof(got));int ok=r&&q&&g&&o&&fg_vk_qsa_attention(context,o,r,q,g,1u,&error)==FG_OK&&fg_vk_tensor_read(o,0,got,sizeof(got),&error)==FG_OK;for(uint32_t head=0;ok&&head<24u;head++){uint32_t kv=head/12u;for(uint32_t i=0;i<256u;i++)if(fabsf(got[head*256u+i]-decoded[kv*256u+i]*0.5f)>2e-6f){fprintf(stderr,"QSA single %u GPU=%g CPU=%g\n",head*256u+i,got[head*256u+i],decoded[kv*256u+i]*0.5f);ok=0;break;}}fg_vk_tensor_destroy(o);fg_vk_tensor_destroy(g);fg_vk_tensor_destroy(q);fg_vk_tensor_destroy(r);return ok;}
static int test_swiglu(void){enum{VALUES=1280};float gate[VALUES],up[VALUES],got[VALUES];for(uint32_t i=0;i<VALUES;i++){gate[i]=sinf((float)i*0.03f)*4.0f;up[i]=cosf((float)i*0.017f)*2.0f;}fg_vk_tensor *g=tensor(gate,sizeof(gate)),*u=tensor(up,sizeof(up)),*o=tensor(NULL,sizeof(got));int ok=g&&u&&o&&fg_vk_swiglu(context,o,g,u,VALUES,&error)==FG_OK&&fg_vk_tensor_read(o,0,got,sizeof(got),&error)==FG_OK;for(uint32_t i=0;ok&&i<VALUES;i++){float ref=gate[i]/(1.0f+expf(-gate[i]))*up[i];if(fabsf(got[i]-ref)>2e-6f)ok=0;}fg_vk_tensor_destroy(o);fg_vk_tensor_destroy(u);fg_vk_tensor_destroy(g);return ok;}
static int test_dense_f32_and_silu(void){enum{INPUT=96,OUTPUT=17,TOKENS=2};float weights[INPUT*OUTPUT],input[INPUT*TOKENS],dense[OUTPUT*TOKENS],silu[OUTPUT*TOKENS];for(uint32_t i=0;i<INPUT*OUTPUT;i++)weights[i]=sinf((float)i*0.021f);for(uint32_t i=0;i<INPUT*TOKENS;i++)input[i]=cosf((float)i*0.037f);fg_vk_tensor *w=tensor(weights,sizeof(weights)),*x=tensor(input,sizeof(input)),*d=tensor(NULL,sizeof(dense)),*s=tensor(NULL,sizeof(silu));int ok=w&&x&&d&&s&&fg_vk_dense_f32(context,d,w,x,INPUT,OUTPUT,TOKENS,&error)==FG_OK&&fg_vk_silu_scaled(context,s,d,OUTPUT*TOKENS,0.25f,&error)==FG_OK&&fg_vk_tensor_read(d,0,dense,sizeof(dense),&error)==FG_OK&&fg_vk_tensor_read(s,0,silu,sizeof(silu),&error)==FG_OK;for(uint32_t token=0;ok&&token<TOKENS;token++)for(uint32_t row=0;ok&&row<OUTPUT;row++){float ref=0.0f;for(uint32_t i=0;i<INPUT;i++)ref=fmaf(weights[row*INPUT+i],input[token*INPUT+i],ref);float activated=(ref*0.25f)/(1.0f+expf(-ref*0.25f));if(fabsf(dense[token*OUTPUT+row]-ref)>2e-4f*fmaxf(1.0f,fabsf(ref))||fabsf(silu[token*OUTPUT+row]-activated)>2e-5f)ok=0;}fg_vk_tensor_destroy(s);fg_vk_tensor_destroy(d);fg_vk_tensor_destroy(x);fg_vk_tensor_destroy(w);return ok;}

static int test_group_norm(void){
    enum{WIDTH=2560,GROUPS=4,TOTAL=WIDTH*GROUPS};float *x=malloc(TOTAL*4u),*w=malloc(TOTAL*4u),*got=malloc(TOTAL*4u),*ref=malloc(TOTAL*4u);if(!x||!w||!got||!ref){free(ref);free(got);free(w);free(x);return 0;}
    for(uint32_t i=0;i<TOTAL;i++){x[i]=sinf((float)i*0.007f)+0.1f;w[i]=cosf((float)i*0.003f)*0.05f;}fg_q38_group_rms_norm(ref,x,w,GROUPS,WIDTH,1e-6f);
    fg_vk_tensor *gx=tensor(x,TOTAL*4u),*gw=tensor(w,TOTAL*4u),*gy=tensor(NULL,TOTAL*4u);int ok=gx&&gw&&gy&&fg_vk_group_rms_norm(context,gy,gx,gw,WIDTH,GROUPS,1,1e-6f,&error)==FG_OK&&fg_vk_tensor_read(gy,0,got,TOTAL*4u,&error)==FG_OK;
    for(uint32_t i=0;ok&&i<TOTAL;i++)if(fabsf(got[i]-ref[i])>2e-5f)ok=0;
    fg_vk_tensor_destroy(gy);fg_vk_tensor_destroy(gw);fg_vk_tensor_destroy(gx);free(ref);free(got);free(w);free(x);return ok;
}

static int test_gr_mix(void){
    enum{HIDDEN=2560,GROUPS=4,HYPER=HIDDEN*GROUPS};float *norm=malloc(HYPER*4u),*up=malloc(HYPER*4u),*mixed=malloc(HIDDEN*4u),*written=malloc(HYPER*4u);float inject_logits[GROUPS]={-2,-1,1,2},injection[GROUPS];if(!norm||!up||!mixed||!written){free(written);free(mixed);free(up);free(norm);return 0;}for(uint32_t i=0;i<HYPER;i++){norm[i]=sinf((float)i*0.01f);up[i]=cosf((float)i*0.02f);}
    fg_vk_tensor *gn=tensor(norm,HYPER*4u),*gu=tensor(up,HYPER*4u),*gi=tensor(inject_logits,sizeof(inject_logits)),*gm=tensor(NULL,HIDDEN*4u),*go=tensor(NULL,sizeof(injection)),*gw=tensor(NULL,HYPER*4u);int ok=gn&&gu&&gi&&gm&&go&&gw&&fg_vk_gr_mix(context,gm,go,gn,gu,gi,HIDDEN,GROUPS,1,&error)==FG_OK&&fg_vk_gr_write(context,gw,gn,gm,go,HIDDEN,GROUPS,1,&error)==FG_OK&&fg_vk_tensor_read(gm,0,mixed,HIDDEN*4u,&error)==FG_OK&&fg_vk_tensor_read(go,0,injection,sizeof(injection),&error)==FG_OK&&fg_vk_tensor_read(gw,0,written,HYPER*4u,&error)==FG_OK;
    for(uint32_t i=0;ok&&i<HIDDEN;i++){float ref=0.0f;for(uint32_t g=0;g<GROUPS;g++){uint32_t j=g*HIDDEN+i;ref+=norm[j]/(1.0f+expf(-up[j]));}ref/=GROUPS;if(fabsf(mixed[i]-ref)>2e-6f)ok=0;}for(uint32_t g=0;ok&&g<GROUPS;g++){float ref=2.0f/(1.0f+expf(-inject_logits[g]/GROUPS));if(fabsf(injection[g]-ref)>1e-6f)ok=0;}
    for(uint32_t g=0;ok&&g<GROUPS;g++)for(uint32_t i=0;ok&&i<HIDDEN;i++)if(fabsf(written[g*HIDDEN+i]-(norm[g*HIDDEN+i]+mixed[i]*injection[g]))>2e-6f)ok=0;
    fg_vk_tensor_destroy(gw);fg_vk_tensor_destroy(go);fg_vk_tensor_destroy(gm);fg_vk_tensor_destroy(gi);fg_vk_tensor_destroy(gu);fg_vk_tensor_destroy(gn);free(written);free(mixed);free(up);free(norm);return ok;
}

static int test_hc_inject_partial(void){
    enum{HIDDEN=2560,GROUPS=4,HYPER=HIDDEN*GROUPS,PIECES=24,ITERATIONS=24};float *normalized=malloc(HYPER*4u),*up=malloc(HYPER*4u),*weights=malloc((size_t)GROUPS*HYPER*4u),mixed_expected[HIDDEN],mixed_got[HIDDEN],inject_logits[GROUPS],injection_expected[GROUPS],injection_got[GROUPS];if(!normalized||!up||!weights){free(weights);free(up);free(normalized);return 0;}
    for(uint32_t i=0;i<HYPER;i++){normalized[i]=sinf((float)i*0.0031f);up[i]=cosf((float)i*0.0027f);}for(uint32_t i=0;i<GROUPS*HYPER;i++)weights[i]=sinf((float)i*0.00017f)*0.125f;for(uint32_t group=0;group<GROUPS;group++){float dot=0.0f;for(uint32_t i=0;i<HYPER;i++)dot=fmaf(weights[(uint64_t)group*HYPER+i],normalized[i],dot);inject_logits[group]=dot;injection_expected[group]=2.0f/(1.0f+expf(-dot/(float)GROUPS));}for(uint32_t i=0;i<HIDDEN;i++){float value=0.0f;for(uint32_t group=0;group<GROUPS;group++){uint32_t index=group*HIDDEN+i;value=fmaf(1.0f/(1.0f+expf(-up[index])),normalized[index],value);}mixed_expected[i]=value/(float)GROUPS;}
    fg_vk_tensor *gn=tensor(normalized,HYPER*4u),*gu=tensor(up,HYPER*4u),*gw=tensor(weights,(uint64_t)GROUPS*HYPER*4u),*gp=tensor(NULL,PIECES*GROUPS*4u),*gm=tensor(NULL,HIDDEN*4u),*gi=tensor(NULL,GROUPS*4u),*gl=tensor(inject_logits,sizeof(inject_logits)),*gom=tensor(NULL,HIDDEN*4u),*goi=tensor(NULL,GROUPS*4u);int ok=gn&&gu&&gw&&gp&&gm&&gi&&gl&&gom&&goi&&fg_vk_begin(context,&error)==FG_OK&&fg_vk_hc_inject_partial(context,gp,gn,gw,HIDDEN,GROUPS,1u,PIECES,&error)==FG_OK&&fg_vk_gr_mix_partial(context,gm,gi,gn,gu,gp,HIDDEN,GROUPS,1u,PIECES,&error)==FG_OK&&fg_vk_end(context,&error)==FG_OK&&fg_vk_tensor_read(gm,0,mixed_got,sizeof(mixed_got),&error)==FG_OK&&fg_vk_tensor_read(gi,0,injection_got,sizeof(injection_got),&error)==FG_OK;for(uint32_t i=0;ok&&i<HIDDEN;i++)if(fabsf(mixed_got[i]-mixed_expected[i])>2e-6f){fprintf(stderr,"HC partial mixed %u GPU=%g CPU=%g diff=%g\n",i,mixed_got[i],mixed_expected[i],mixed_got[i]-mixed_expected[i]);ok=0;}for(uint32_t group=0;ok&&group<GROUPS;group++)if(fabsf(injection_got[group]-injection_expected[group])>2e-5f*fmaxf(1.0f,fabsf(injection_expected[group]))){fprintf(stderr,"HC partial injection %u GPU=%g CPU=%g diff=%g\n",group,injection_got[group],injection_expected[group],injection_got[group]-injection_expected[group]);ok=0;}
    if(ok&&getenv("FG_BENCH_HC_INJECT")){fg_vk_profile old_profile={0},new_profile={0};struct timespec start,end;clock_gettime(CLOCK_MONOTONIC,&start);ok=fg_vk_profile_begin(context,&error)==FG_OK&&fg_vk_begin(context,&error)==FG_OK;for(uint32_t i=0;ok&&i<ITERATIONS;i++)ok=fg_vk_dense_f32(context,gl,gw,gn,HYPER,GROUPS,1u,&error)==FG_OK&&fg_vk_gr_mix(context,gom,goi,gn,gu,gl,HIDDEN,GROUPS,1u,&error)==FG_OK;if(ok)ok=fg_vk_end(context,&error)==FG_OK&&fg_vk_profile_end(context,&old_profile,&error)==FG_OK;clock_gettime(CLOCK_MONOTONIC,&end);double old_wall=((double)(end.tv_sec-start.tv_sec)*1e3+(double)(end.tv_nsec-start.tv_nsec)*1e-6)/(double)ITERATIONS;clock_gettime(CLOCK_MONOTONIC,&start);ok=ok&&fg_vk_profile_begin(context,&error)==FG_OK&&fg_vk_begin(context,&error)==FG_OK;for(uint32_t i=0;ok&&i<ITERATIONS;i++)ok=fg_vk_hc_inject_partial(context,gp,gn,gw,HIDDEN,GROUPS,1u,PIECES,&error)==FG_OK&&fg_vk_gr_mix_partial(context,gm,gi,gn,gu,gp,HIDDEN,GROUPS,1u,PIECES,&error)==FG_OK;if(ok)ok=fg_vk_end(context,&error)==FG_OK&&fg_vk_profile_end(context,&new_profile,&error)==FG_OK;clock_gettime(CLOCK_MONOTONIC,&end);double new_wall=((double)(end.tv_sec-start.tv_sec)*1e3+(double)(end.tv_nsec-start.tv_nsec)*1e-6)/(double)ITERATIONS;if(ok)fprintf(stderr,"HC_INJECT_BENCH iterations=%u old_gpu_us=%.3f new_gpu_us=%.3f old_wall_us=%.3f new_wall_us=%.3f\n",ITERATIONS,old_profile.gpu_ms*1000.0/(double)ITERATIONS,new_profile.gpu_ms*1000.0/(double)ITERATIONS,old_wall*1000.0,new_wall*1000.0);}
    fg_vk_tensor_destroy(goi);fg_vk_tensor_destroy(gom);fg_vk_tensor_destroy(gl);fg_vk_tensor_destroy(gi);fg_vk_tensor_destroy(gm);fg_vk_tensor_destroy(gp);fg_vk_tensor_destroy(gw);fg_vk_tensor_destroy(gu);fg_vk_tensor_destroy(gn);free(weights);free(up);free(normalized);return ok;
}

static int test_gr_batch(void){
    enum{TOKENS=3,HIDDEN=32,GROUPS=4,HYPER=HIDDEN*GROUPS};float normalized[TOKENS*HYPER],up[TOKENS*HYPER],inject_logits[TOKENS*GROUPS],mixed[TOKENS*HIDDEN],injection[TOKENS*GROUPS],written[TOKENS*HYPER];for(uint32_t token=0;token<TOKENS;token++){for(uint32_t group=0;group<GROUPS;group++)inject_logits[token*GROUPS+group]=(float)((int32_t)token-(int32_t)group)*0.7f;for(uint32_t i=0;i<HYPER;i++){normalized[token*HYPER+i]=sinf((float)(token*HYPER+i)*0.019f);up[token*HYPER+i]=cosf((float)(token*HYPER+i)*0.023f);}}
    fg_vk_tensor *n=tensor(normalized,sizeof(normalized)),*u=tensor(up,sizeof(up)),*il=tensor(inject_logits,sizeof(inject_logits)),*m=tensor(NULL,sizeof(mixed)),*in=tensor(NULL,sizeof(injection)),*w=tensor(NULL,sizeof(written));int ok=n&&u&&il&&m&&in&&w&&fg_vk_gr_mix(context,m,in,n,u,il,HIDDEN,GROUPS,TOKENS,&error)==FG_OK&&fg_vk_gr_write(context,w,n,m,in,HIDDEN,GROUPS,TOKENS,&error)==FG_OK&&fg_vk_tensor_read(m,0,mixed,sizeof(mixed),&error)==FG_OK&&fg_vk_tensor_read(in,0,injection,sizeof(injection),&error)==FG_OK&&fg_vk_tensor_read(w,0,written,sizeof(written),&error)==FG_OK;
    for(uint32_t token=0;ok&&token<TOKENS;token++){for(uint32_t i=0;i<HIDDEN;i++){float expected=0.0f;for(uint32_t group=0;group<GROUPS;group++){uint32_t index=token*HYPER+group*HIDDEN+i;expected+=normalized[index]/(1.0f+expf(-up[index]));}expected/=GROUPS;if(fabsf(mixed[token*HIDDEN+i]-expected)>2e-6f)ok=0;}for(uint32_t group=0;ok&&group<GROUPS;group++){float scale=2.0f/(1.0f+expf(-inject_logits[token*GROUPS+group]/GROUPS));if(fabsf(injection[token*GROUPS+group]-scale)>1e-6f)ok=0;for(uint32_t i=0;ok&&i<HIDDEN;i++){uint32_t index=token*HYPER+group*HIDDEN+i;float expected=normalized[index]+mixed[token*HIDDEN+i]*scale;if(fabsf(written[index]-expected)>2e-6f)ok=0;}}}
    fg_vk_tensor_destroy(w);fg_vk_tensor_destroy(in);fg_vk_tensor_destroy(m);fg_vk_tensor_destroy(il);fg_vk_tensor_destroy(u);fg_vk_tensor_destroy(n);return ok;
}

static int test_q5_1_down(void){
    enum{INPUT=640,OUTPUT=8};uint8_t weights[OUTPUT*(INPUT/32)*24];float x[INPUT],got[OUTPUT];uint32_t tiles[9];for(uint32_t i=0;i<9;i++)tiles[i]=UINT32_MAX;tiles[0]=0;tiles[1]=0;for(uint32_t r=0;r<OUTPUT;r++)make_q5_1_row(weights+(uint64_t)r*(INPUT/32)*24,INPUT,r);for(uint32_t i=0;i<INPUT;i++)x[i]=sinf((float)i*0.03125f);
    fg_vk_tensor *w=tensor(weights,sizeof(weights)),*schedule=tensor(tiles,sizeof(tiles)),*input=tensor(x,sizeof(x)),*output=tensor(NULL,sizeof(got));int ok=w&&schedule&&input&&output&&fg_vk_moe_q5_1_down(context,output,w,schedule,input,OUTPUT,INPUT,sizeof(weights),1,false,1,&error)==FG_OK&&fg_vk_tensor_read(output,0,got,sizeof(got),&error)==FG_OK;
    for(uint32_t r=0;ok&&r<OUTPUT;r++){float ref=fg_q5_1_dot_f32(weights+(uint64_t)r*(INPUT/32)*24,x,INPUT);if(fabsf(got[r]-ref)>1e-4f*fmaxf(1.0f,fabsf(ref)))ok=0;}fg_vk_tensor_destroy(output);fg_vk_tensor_destroy(input);fg_vk_tensor_destroy(schedule);fg_vk_tensor_destroy(w);return ok;
}

static int test_q8_0_down(void){
    enum{INPUT=640,OUTPUT=8};float *source=malloc((size_t)INPUT*OUTPUT*4u),x[INPUT],got[OUTPUT];uint8_t *weights=malloc((size_t)OUTPUT*(INPUT/32u)*FG_Q8_0_BLOCK_BYTES);uint32_t tiles[9];for(uint32_t i=0;i<9;i++)tiles[i]=UINT32_MAX;tiles[0]=0;tiles[1]=0;if(!source||!weights){free(weights);free(source);return 0;}for(uint32_t i=0;i<INPUT;i++)x[i]=cosf((float)i*0.017f);for(uint32_t row=0;row<OUTPUT;row++){for(uint32_t i=0;i<INPUT;i++)source[row*INPUT+i]=sinf((float)(row*INPUT+i)*0.009f);fg_quantize_q8_0(source+row*INPUT,weights+(uint64_t)row*(INPUT/32u)*FG_Q8_0_BLOCK_BYTES,INPUT);}
    uint32_t expert_stride=OUTPUT*(INPUT/32u)*FG_Q8_0_BLOCK_BYTES;fg_vk_tensor *w=tensor(weights,expert_stride),*schedule=tensor(tiles,sizeof(tiles)),*input=tensor(x,sizeof(x)),*output=tensor(NULL,sizeof(got));int ok=w&&schedule&&input&&output&&fg_vk_moe_q8_0_down(context,output,w,schedule,input,OUTPUT,INPUT,expert_stride,1,false,1,&error)==FG_OK&&fg_vk_tensor_read(output,0,got,sizeof(got),&error)==FG_OK;
    for(uint32_t row=0;ok&&row<OUTPUT;row++){float ref=0.0f;const uint8_t *blocks=weights+(uint64_t)row*(INPUT/32u)*FG_Q8_0_BLOCK_BYTES;for(uint32_t block=0;block<INPUT/32u;block++){const uint8_t *p=blocks+block*FG_Q8_0_BLOCK_BYTES;float d=fg_f16_to_f32((uint16_t)p[0]|(uint16_t)((uint16_t)p[1]<<8u));for(uint32_t i=0;i<32u;i++)ref=fmaf(d*(float)(int8_t)p[2u+i],x[block*32u+i],ref);}if(fabsf(got[row]-ref)>2e-4f*fmaxf(1.0f,fabsf(ref)))ok=0;}
    fg_vk_tensor_destroy(output);fg_vk_tensor_destroy(input);fg_vk_tensor_destroy(schedule);fg_vk_tensor_destroy(w);free(weights);free(source);return ok;
}

static int test_moe_reduce(void){
    enum{WIDTH=513,SLOTS=4,SELECTED=3};float down[SLOTS*WIDTH],gates[SELECTED]={0.25f,-0.75f,1.5f},got[WIDTH],expected[WIDTH];uint32_t tiles[SELECTED*9u];for(uint32_t i=0;i<SELECTED*9u;i++)tiles[i]=UINT32_MAX;tiles[1]=3u;tiles[10]=0u;tiles[19]=2u;for(uint32_t slot=0;slot<SLOTS;slot++)for(uint32_t i=0;i<WIDTH;i++)down[slot*WIDTH+i]=sinf((float)(slot*WIDTH+i)*0.013f);for(uint32_t i=0;i<WIDTH;i++){expected[i]=0.0f;for(uint32_t selected=0;selected<SELECTED;selected++)expected[i]=fmaf(gates[selected],down[tiles[selected*9u+1u]*WIDTH+i],expected[i]);}
    fg_vk_tensor *gd=tensor(down,sizeof(down)),*gg=tensor(gates,sizeof(gates)),*gt=tensor(tiles,sizeof(tiles)),*go=tensor(NULL,sizeof(got));int ok=gd&&gg&&gt&&go&&fg_vk_moe_reduce(context,go,gd,gg,gt,WIDTH,SELECTED,SLOTS,&error)==FG_OK&&fg_vk_tensor_read(go,0,got,sizeof(got),&error)==FG_OK;for(uint32_t i=0;ok&&i<WIDTH;i++)if(fabsf(got[i]-expected[i])>2e-6f*fmaxf(1.0f,fabsf(expected[i]))){fprintf(stderr,"MoE reduce %u GPU=%g CPU=%g diff=%g\n",i,got[i],expected[i],got[i]-expected[i]);ok=0;}fg_vk_tensor_destroy(go);fg_vk_tensor_destroy(gt);fg_vk_tensor_destroy(gg);fg_vk_tensor_destroy(gd);return ok;
}

static void make_k_row(uint8_t *block,int q5,uint32_t phase){
    uint16_t d=fg_f32_to_f16(0.25f),dmin=fg_f32_to_f16(0.03125f);memcpy(block,&d,2);memcpy(block+2,&dmin,2);
    for(uint32_t group=0;group<8u;group++){uint32_t scale=group+1u,minimum=8u-group;if(group<4u){block[4u+group]=(uint8_t)scale;block[8u+group]=(uint8_t)minimum;}else block[8u+group]=(uint8_t)(scale|(minimum<<4u));}
    for(uint32_t group=0;group<8u;group++)for(uint32_t i=0;i<32u;i++){uint32_t value=(group*3u+i+phase)&(q5?31u:15u);uint32_t packed_offset=(q5?48u:16u)+(group>>1u)*32u+i;if(group&1u)block[packed_offset]|=(uint8_t)((value&15u)<<4u);else block[packed_offset]|=(uint8_t)(value&15u);if(q5&&(value&16u))block[16u+i]|=(uint8_t)(1u<<group);}
}

static int test_kquant(int type){
    enum{INPUT=256,OUTPUT=8};uint32_t block_bytes=type==12?144u:176u;uint8_t *weights=calloc(OUTPUT,block_bytes);float x[INPUT],got[OUTPUT];uint8_t q8[FG_Q8_K_BLOCK_BYTES];uint32_t tiles[9];for(uint32_t i=0;i<9;i++)tiles[i]=UINT32_MAX;tiles[0]=0;tiles[1]=0;if(!weights)return 0;for(uint32_t row=0;row<OUTPUT;row++)make_k_row(weights+row*block_bytes,type==13,row);for(uint32_t i=0;i<INPUT;i++)x[i]=sinf((float)i*0.019f);fg_quantize_q8_k(x,q8,INPUT);
    fg_vk_tensor *w=tensor(weights,(uint64_t)OUTPUT*block_bytes),*activation=tensor(q8,sizeof(q8)),*schedule=tensor(tiles,sizeof(tiles)),*output=tensor(NULL,sizeof(got));int ok=w&&activation&&schedule&&output&&fg_vk_moe_kquant(context,output,w,activation,schedule,(uint32_t)type,OUTPUT,INPUT,OUTPUT*block_bytes,1,1,false,1,&error)==FG_OK&&fg_vk_tensor_read(output,0,got,sizeof(got),&error)==FG_OK;
    for(uint32_t row=0;ok&&row<OUTPUT;row++){float ref=type==12?fg_dot_q4_k_q8_k(weights+row*block_bytes,q8,INPUT):fg_dot_q5_k_q8_k(weights+row*block_bytes,q8,INPUT);if(fabsf(got[row]-ref)>2e-4f*fmaxf(1.0f,fabsf(ref))){fprintf(stderr,"K-quant type %d row %u GPU=%g CPU=%g\n",type,row,got[row],ref);ok=0;}}
    fg_vk_tensor_destroy(output);fg_vk_tensor_destroy(schedule);fg_vk_tensor_destroy(activation);fg_vk_tensor_destroy(w);free(weights);return ok;
}

static int test_kquant_expert_major_batch(int type){
    enum{INPUT=256,OUTPUT=8,EXPERTS=2,TOKENS=3,PAIRS=EXPERTS*TOKENS};uint32_t block_bytes=type==12?144u:176u,expert_stride=OUTPUT*block_bytes;
    uint8_t *weights=calloc(EXPERTS,expert_stride),activations[TOKENS*FG_Q8_K_BLOCK_BYTES];float input[TOKENS][INPUT],got[PAIRS*OUTPUT];uint32_t tiles[18];if(!weights)return 0;for(uint32_t i=0;i<18u;i++)tiles[i]=UINT32_MAX;tiles[0]=0;tiles[1]=0;tiles[2]=2;tiles[3]=4;tiles[9]=1;tiles[10]=1;tiles[11]=3;tiles[12]=5;
    for(uint32_t expert=0;expert<EXPERTS;expert++)for(uint32_t row=0;row<OUTPUT;row++)make_k_row(weights+(uint64_t)expert*expert_stride+row*block_bytes,type==13,expert*17u+row);
    for(uint32_t token=0;token<TOKENS;token++){for(uint32_t i=0;i<INPUT;i++)input[token][i]=sinf((float)(token+1u)*(float)(i+3u)*0.013f)+0.1f*cosf((float)(i+token)*0.031f);fg_quantize_q8_k(input[token],activations+token*FG_Q8_K_BLOCK_BYTES,INPUT);}
    fg_vk_tensor *w=tensor(weights,(uint64_t)EXPERTS*expert_stride),*a=tensor(activations,sizeof(activations)),*schedule=tensor(tiles,sizeof(tiles)),*output=tensor(NULL,sizeof(got));int ok=w&&a&&schedule&&output&&fg_vk_moe_kquant(context,output,w,a,schedule,(uint32_t)type,OUTPUT,INPUT,expert_stride,EXPERTS,PAIRS,false,EXPERTS,&error)==FG_OK&&fg_vk_tensor_read(output,0,got,sizeof(got),&error)==FG_OK;
    for(uint32_t pair=0;ok&&pair<PAIRS;pair++){uint32_t token=pair/EXPERTS,expert=pair%EXPERTS;const uint8_t *q8=activations+token*FG_Q8_K_BLOCK_BYTES;for(uint32_t row=0;row<OUTPUT;row++){const uint8_t *weight=weights+(uint64_t)expert*expert_stride+row*block_bytes;float ref=type==12?fg_dot_q4_k_q8_k(weight,q8,INPUT):fg_dot_q5_k_q8_k(weight,q8,INPUT);if(fabsf(got[pair*OUTPUT+row]-ref)>2e-4f*fmaxf(1.0f,fabsf(ref))){fprintf(stderr,"expert-major K-quant type %d pair %u row %u GPU=%g CPU=%g\n",type,pair,row,got[pair*OUTPUT+row],ref);ok=0;break;}}}
    fg_vk_tensor_destroy(output);fg_vk_tensor_destroy(schedule);fg_vk_tensor_destroy(a);fg_vk_tensor_destroy(w);free(weights);return ok;
}

static int test_expert_graph_replay(void){
    enum{HIDDEN=256,MID=32,SLOTS=4,EXPERTS=2,PASSES=2};uint32_t gate_block=144u,up_block=176u,down_row=(MID/32u)*FG_Q8_0_BLOCK_BYTES,gate_stride=MID*gate_block,up_stride=MID*up_block,down_stride=HIDDEN*down_row;uint8_t *gate_weights=calloc(EXPERTS,gate_stride),*up_weights=calloc(EXPERTS,up_stride),*down_weights=malloc((size_t)EXPERTS*down_stride);float *down_source=malloc((size_t)EXPERTS*HIDDEN*MID*4u);if(!gate_weights||!up_weights||!down_weights||!down_source){free(down_source);free(down_weights);free(up_weights);free(gate_weights);return 0;}
    for(uint32_t expert=0;expert<EXPERTS;expert++){for(uint32_t row=0;row<MID;row++){make_k_row(gate_weights+(uint64_t)expert*gate_stride+row*gate_block,0,expert*13u+row);make_k_row(up_weights+(uint64_t)expert*up_stride+row*up_block,1,expert*17u+row);}for(uint32_t row=0;row<HIDDEN;row++){float *source=down_source+((uint64_t)expert*HIDDEN+row)*MID;for(uint32_t i=0;i<MID;i++)source[i]=sinf((float)(expert*HIDDEN*MID+row*MID+i)*0.009f);fg_quantize_q8_0(source,down_weights+(uint64_t)expert*down_stride+row*down_row,MID);}}
    fg_vk_tensor *gw=tensor(gate_weights,(uint64_t)EXPERTS*gate_stride),*uw=tensor(up_weights,(uint64_t)EXPERTS*up_stride),*dw=tensor(down_weights,(uint64_t)EXPERTS*down_stride),*activation=tensor(NULL,FG_Q8_K_BLOCK_BYTES),*tiles=tensor(NULL,SLOTS*9u*4u),*gates=tensor(NULL,SLOTS*4u),*gate=tensor(NULL,SLOTS*MID*4u),*up=tensor(NULL,SLOTS*MID*4u),*mid=tensor(NULL,SLOTS*MID*4u),*down=tensor(NULL,SLOTS*HIDDEN*4u),*reduced=tensor(NULL,HIDDEN*4u);fg_vk_expert_graph *graph=NULL;int ok=gw&&uw&&dw&&activation&&tiles&&gates&&gate&&up&&mid&&down&&reduced&&fg_vk_expert_graph_create(context,&graph,activation,tiles,gates,gate,up,mid,down,reduced,gw,uw,dw,12u,13u,8u,HIDDEN,MID,gate_stride,up_stride,down_stride,EXPERTS,SLOTS,&error)==FG_OK;
    for(uint32_t pass=0;ok&&pass<PASSES;pass++){uint32_t selected_count=pass+1u;float input[HIDDEN],gate_values[SLOTS]={0},expected[HIDDEN],got[HIDDEN],poison_gate[SLOTS*MID],poison_up[SLOTS*MID],poison_mid[SLOTS*MID],poison_down[SLOTS*HIDDEN],poison_reduced[HIDDEN];uint8_t q8[FG_Q8_K_BLOCK_BYTES];uint32_t schedule[SLOTS*9u];for(uint32_t i=0;i<SLOTS*9u;i++)schedule[i]=UINT32_MAX;for(uint32_t i=0;i<HIDDEN;i++){input[i]=sinf((float)(pass+1u)*(float)(i+3u)*0.017f)+0.1f*cosf((float)(i+pass)*0.031f);poison_reduced[i]=1234.0f;for(uint32_t slot=0;slot<SLOTS;slot++)poison_down[slot*HIDDEN+i]=1234.0f;}for(uint32_t i=0;i<SLOTS*MID;i++){poison_gate[i]=1234.0f;poison_up[i]=1234.0f;poison_mid[i]=1234.0f;}fg_quantize_q8_k(input,q8,HIDDEN);for(uint32_t selected=0;selected<selected_count;selected++){schedule[selected*9u]=(selected+pass)%EXPERTS;schedule[selected*9u+1u]=(selected*2u+pass)%SLOTS;gate_values[selected]=(pass?0.65f:-0.35f)+(float)selected*0.4f;}ok=fg_vk_tensor_write(activation,0,q8,sizeof(q8),&error)==FG_OK&&fg_vk_tensor_write(tiles,0,schedule,sizeof(schedule),&error)==FG_OK&&fg_vk_tensor_write(gates,0,gate_values,sizeof(gate_values),&error)==FG_OK&&fg_vk_begin(context,&error)==FG_OK&&fg_vk_moe_kquant(context,gate,gw,activation,tiles,12u,MID,HIDDEN,gate_stride,SLOTS,SLOTS,false,selected_count,&error)==FG_OK&&fg_vk_moe_kquant(context,up,uw,activation,tiles,13u,MID,HIDDEN,up_stride,SLOTS,SLOTS,false,selected_count,&error)==FG_OK&&fg_vk_swiglu(context,mid,gate,up,SLOTS*MID,&error)==FG_OK&&fg_vk_moe_q8_0_down(context,down,dw,tiles,mid,HIDDEN,MID,down_stride,SLOTS,false,selected_count,&error)==FG_OK&&fg_vk_moe_reduce(context,reduced,down,gates,tiles,HIDDEN,selected_count,SLOTS,&error)==FG_OK&&fg_vk_end(context,&error)==FG_OK&&fg_vk_tensor_read(reduced,0,expected,sizeof(expected),&error)==FG_OK&&fg_vk_tensor_write(gate,0,poison_gate,sizeof(poison_gate),&error)==FG_OK&&fg_vk_tensor_write(up,0,poison_up,sizeof(poison_up),&error)==FG_OK&&fg_vk_tensor_write(mid,0,poison_mid,sizeof(poison_mid),&error)==FG_OK&&fg_vk_tensor_write(down,0,poison_down,sizeof(poison_down),&error)==FG_OK&&fg_vk_tensor_write(reduced,0,poison_reduced,sizeof(poison_reduced),&error)==FG_OK;fg_vk_counters before,after;fg_vk_get_counters(context,&before);if(ok)ok=fg_vk_expert_graph_execute(graph,&error)==FG_OK&&fg_vk_tensor_read(reduced,0,got,sizeof(got),&error)==FG_OK;fg_vk_get_counters(context,&after);if(ok&&(after.submissions!=before.submissions+1u||after.dispatches!=before.dispatches+5u)){fprintf(stderr,"expert graph counters submissions=%llu dispatches=%llu\n",(unsigned long long)(after.submissions-before.submissions),(unsigned long long)(after.dispatches-before.dispatches));ok=0;}for(uint32_t i=0;ok&&i<HIDDEN;i++)if(got[i]!=expected[i]){fprintf(stderr,"expert graph pass %u value %u replay=%g dynamic=%g diff=%g\n",pass,i,got[i],expected[i],got[i]-expected[i]);ok=0;}}
    fg_vk_expert_graph_destroy(graph);fg_vk_tensor_destroy(reduced);fg_vk_tensor_destroy(down);fg_vk_tensor_destroy(mid);fg_vk_tensor_destroy(up);fg_vk_tensor_destroy(gate);fg_vk_tensor_destroy(gates);fg_vk_tensor_destroy(tiles);fg_vk_tensor_destroy(activation);fg_vk_tensor_destroy(dw);fg_vk_tensor_destroy(uw);fg_vk_tensor_destroy(gw);free(down_source);free(down_weights);free(up_weights);free(gate_weights);return ok;
}

static float softplus_ref(float value){return fmaxf(value,0.0f)+log1pf(expf(-fabsf(value)));}
static int test_gdn_decode(void){
    enum{VALUE_HEADS=48,KEY_HEADS=16,DIM=128,KEY_WIDTH=KEY_HEADS*DIM,VALUE_WIDTH=VALUE_HEADS*DIM,QKV_WIDTH=2*KEY_WIDTH+VALUE_WIDTH,STATE_VALUES=VALUE_HEADS*DIM*DIM};
    float *projection=malloc(QKV_WIDTH*4u),*conv_weight=malloc(QKV_WIDTH*4u*4u),*conv_state=malloc(QKV_WIDTH*4u*4u),*conv_expected=malloc(QKV_WIDTH*4u),*conv_got=malloc(QKV_WIDTH*4u);if(!projection||!conv_weight||!conv_state||!conv_expected||!conv_got)return 0;
    for(uint32_t i=0;i<QKV_WIDTH;i++){projection[i]=sinf((float)i*0.013f);for(uint32_t k=0;k<4u;k++){conv_weight[i*4u+k]=cosf((float)(i*4u+k)*0.017f)*0.2f;conv_state[i*4u+k]=sinf((float)(i*4u+k)*0.009f)*0.1f;}float value=conv_weight[i*4u]*conv_state[i*4u+1u]+conv_weight[i*4u+1u]*conv_state[i*4u+2u]+conv_weight[i*4u+2u]*conv_state[i*4u+3u]+conv_weight[i*4u+3u]*projection[i];conv_expected[i]=value/(1.0f+expf(-value));}
    fg_vk_tensor *gp=tensor(projection,QKV_WIDTH*4u),*gcw=tensor(conv_weight,QKV_WIDTH*16u),*gcs=tensor(conv_state,QKV_WIDTH*16u),*gco=tensor(NULL,QKV_WIDTH*4u);int ok=gp&&gcw&&gcs&&gco&&fg_vk_gdn_conv_decode(context,gco,gcs,gp,gcw,QKV_WIDTH,&error)==FG_OK&&fg_vk_tensor_read(gco,0,conv_got,QKV_WIDTH*4u,&error)==FG_OK;for(uint32_t i=0;ok&&i<QKV_WIDTH;i++)if(fabsf(conv_got[i]-conv_expected[i])>2e-6f){fprintf(stderr,"GDN conv %u GPU=%g CPU=%g\n",i,conv_got[i],conv_expected[i]);ok=0;}
    float *qkv=conv_got,*z=malloc(VALUE_WIDTH*4u),alpha[VALUE_HEADS],beta[VALUE_HEADS],a_decay[VALUE_HEADS],dt[VALUE_HEADS],norm[DIM],*state=malloc(STATE_VALUES*4u),*cpu_state=malloc(STATE_VALUES*4u),*got=malloc(VALUE_WIDTH*4u),*expected=malloc(VALUE_WIDTH*4u);if(!z||!state||!cpu_state||!got||!expected)ok=0;
    if(ok){for(uint32_t i=0;i<VALUE_WIDTH;i++)z[i]=cosf((float)i*0.011f);for(uint32_t h=0;h<VALUE_HEADS;h++){alpha[h]=sinf((float)h*0.1f);beta[h]=cosf((float)h*0.07f);a_decay[h]=-(0.02f+(float)(h+1u)*0.01f);dt[h]=-0.3f+(float)h*0.005f;}for(uint32_t i=0;i<DIM;i++)norm[i]=0.9f+0.2f*sinf((float)i*0.03f);for(uint32_t i=0;i<STATE_VALUES;i++)state[i]=sinf((float)i*0.0007f)*0.01f;memcpy(cpu_state,state,STATE_VALUES*4u);
        for(uint32_t h=0;h<VALUE_HEADS;h++){uint32_t kh=h%KEY_HEADS;float qnorm=0.0f,knorm=0.0f;for(uint32_t i=0;i<DIM;i++){float q=qkv[kh*DIM+i],k=qkv[KEY_WIDTH+kh*DIM+i];qnorm=fmaf(q,q,qnorm);knorm=fmaf(k,k,knorm);}float qs=1.0f/sqrtf(qnorm+1e-6f)/sqrtf((float)DIM),ks=1.0f/sqrtf(knorm+1e-6f),decay=expf(a_decay[h]*softplus_ref(alpha[h]+dt[h])),mix=1.0f/(1.0f+expf(-beta[h]));float delta[DIM];uint32_t base=h*DIM*DIM;for(uint32_t v=0;v<DIM;v++){float memory=0.0f;for(uint32_t k=0;k<DIM;k++)memory=fmaf(cpu_state[base+k*DIM+v]*decay,qkv[KEY_WIDTH+kh*DIM+k]*ks,memory);delta[v]=(qkv[2*KEY_WIDTH+h*DIM+v]-memory)*mix;}for(uint32_t k=0;k<DIM;k++)for(uint32_t v=0;v<DIM;v++)cpu_state[base+k*DIM+v]=cpu_state[base+k*DIM+v]*decay+qkv[KEY_WIDTH+kh*DIM+k]*ks*delta[v];float ss=0.0f;for(uint32_t v=0;v<DIM;v++){float value=0.0f;for(uint32_t k=0;k<DIM;k++)value=fmaf(cpu_state[base+k*DIM+v],qkv[kh*DIM+k]*qs,value);expected[h*DIM+v]=value;ss=fmaf(value,value,ss);}float scale=1.0f/sqrtf(ss/(float)DIM+1e-6f);for(uint32_t v=0;v<DIM;v++){float gate=z[h*DIM+v];expected[h*DIM+v]*=scale*norm[v]*(1.0f/(1.0f+expf(-gate)));}}
        fg_vk_tensor *gq=tensor(qkv,QKV_WIDTH*4u),*gz=tensor(z,VALUE_WIDTH*4u),*ga=tensor(alpha,sizeof(alpha)),*gb=tensor(beta,sizeof(beta)),*gal=tensor(a_decay,sizeof(a_decay)),*gdt=tensor(dt,sizeof(dt)),*gn=tensor(norm,sizeof(norm)),*gs=tensor(state,STATE_VALUES*4u),*go=tensor(NULL,VALUE_WIDTH*4u);ok=gq&&gz&&ga&&gb&&gal&&gdt&&gn&&gs&&go&&fg_vk_gdn_recurrent_decode(context,go,gs,gq,gz,ga,gb,gal,gdt,gn,VALUE_HEADS,KEY_HEADS,DIM,1e-6f,&error)==FG_OK&&fg_vk_tensor_read(go,0,got,VALUE_WIDTH*4u,&error)==FG_OK&&fg_vk_tensor_read(gs,0,state,STATE_VALUES*4u,&error)==FG_OK;for(uint32_t i=0;ok&&i<VALUE_WIDTH;i++)if(fabsf(got[i]-expected[i])>3e-4f*fmaxf(1.0f,fabsf(expected[i]))){fprintf(stderr,"GDN out %u GPU=%g CPU=%g\n",i,got[i],expected[i]);ok=0;}for(uint32_t i=0;ok&&i<STATE_VALUES;i+=97u)if(fabsf(state[i]-cpu_state[i])>3e-5f){fprintf(stderr,"GDN state %u GPU=%g CPU=%g\n",i,state[i],cpu_state[i]);ok=0;}fg_vk_tensor_destroy(go);fg_vk_tensor_destroy(gs);fg_vk_tensor_destroy(gn);fg_vk_tensor_destroy(gdt);fg_vk_tensor_destroy(gal);fg_vk_tensor_destroy(gb);fg_vk_tensor_destroy(ga);fg_vk_tensor_destroy(gz);fg_vk_tensor_destroy(gq);
    }
    free(expected);free(got);free(cpu_state);free(state);free(z);fg_vk_tensor_destroy(gco);fg_vk_tensor_destroy(gcs);fg_vk_tensor_destroy(gcw);fg_vk_tensor_destroy(gp);free(conv_got);free(conv_expected);free(conv_state);free(conv_weight);free(projection);return ok;
}

static int test_gdn_algebraic(void){
    enum{VALUE_HEADS=48,KEY_HEADS=16,DIM=128,KEY_WIDTH=KEY_HEADS*DIM,VALUE_WIDTH=VALUE_HEADS*DIM,QKV_WIDTH=2*KEY_WIDTH+VALUE_WIDTH,STATE_VALUES=VALUE_HEADS*DIM*DIM,ITERATIONS=24};float *qkv=malloc(QKV_WIDTH*4u),*z=malloc(VALUE_WIDTH*4u),alpha[VALUE_HEADS],beta[VALUE_HEADS],a_decay[VALUE_HEADS],dt[VALUE_HEADS],norm[DIM],*initial=malloc(STATE_VALUES*4u),*state_reference=malloc(STATE_VALUES*4u),*state_candidate=malloc(STATE_VALUES*4u),*reference=malloc(VALUE_WIDTH*4u),*candidate=malloc(VALUE_WIDTH*4u);if(!qkv||!z||!initial||!state_reference||!state_candidate||!reference||!candidate){free(candidate);free(reference);free(state_candidate);free(state_reference);free(initial);free(z);free(qkv);return 0;}for(uint32_t i=0;i<QKV_WIDTH;i++)qkv[i]=sinf((float)i*0.007f)+0.1f*cosf((float)i*0.019f);for(uint32_t i=0;i<VALUE_WIDTH;i++)z[i]=cosf((float)i*0.009f);for(uint32_t head=0;head<VALUE_HEADS;head++){alpha[head]=-0.2f+(float)head*0.01f;beta[head]=0.3f-(float)head*0.007f;a_decay[head]=-0.03f*(float)(head+1u);dt[head]=-0.1f+(float)head*0.002f;}for(uint32_t i=0;i<DIM;i++)norm[i]=0.8f+0.1f*sinf((float)i*0.03f);for(uint32_t i=0;i<STATE_VALUES;i++)initial[i]=sinf((float)i*0.0007f)*0.01f;
    fg_vk_tensor *gq=tensor(qkv,QKV_WIDTH*4u),*gz=tensor(z,VALUE_WIDTH*4u),*ga=tensor(alpha,sizeof(alpha)),*gb=tensor(beta,sizeof(beta)),*gal=tensor(a_decay,sizeof(a_decay)),*gdt=tensor(dt,sizeof(dt)),*gn=tensor(norm,sizeof(norm)),*gsr=tensor(initial,STATE_VALUES*4u),*gsc=tensor(initial,STATE_VALUES*4u),*gor=tensor(NULL,VALUE_WIDTH*4u),*goc=tensor(NULL,VALUE_WIDTH*4u);int ok=gq&&gz&&ga&&gb&&gal&&gdt&&gn&&gsr&&gsc&&gor&&goc&&fg_vk_gdn_recurrent_decode(context,gor,gsr,gq,gz,ga,gb,gal,gdt,gn,VALUE_HEADS,KEY_HEADS,DIM,1e-6f,&error)==FG_OK&&fg_vk_gdn_recurrent_algebraic(context,goc,gsc,gq,gz,ga,gb,gal,gdt,gn,VALUE_HEADS,KEY_HEADS,DIM,1e-6f,&error)==FG_OK&&fg_vk_tensor_read(gor,0,reference,VALUE_WIDTH*4u,&error)==FG_OK&&fg_vk_tensor_read(goc,0,candidate,VALUE_WIDTH*4u,&error)==FG_OK&&fg_vk_tensor_read(gsr,0,state_reference,STATE_VALUES*4u,&error)==FG_OK&&fg_vk_tensor_read(gsc,0,state_candidate,STATE_VALUES*4u,&error)==FG_OK;for(uint32_t i=0;ok&&i<VALUE_WIDTH;i++)if(fabsf(candidate[i]-reference[i])>3e-4f*fmaxf(1.0f,fabsf(reference[i]))){fprintf(stderr,"GDN algebraic out %u candidate=%g reference=%g diff=%g\n",i,candidate[i],reference[i],candidate[i]-reference[i]);ok=0;}for(uint32_t i=0;ok&&i<STATE_VALUES;i++)if(state_candidate[i]!=state_reference[i]){fprintf(stderr,"GDN algebraic state %u candidate=%g reference=%g\n",i,state_candidate[i],state_reference[i]);ok=0;}
    if(ok&&getenv("FG_BENCH_GDN_ALGEBRAIC")){fg_vk_profile old_profile={0},new_profile={0};struct timespec start,end;ok=fg_vk_tensor_write(gsr,0,initial,STATE_VALUES*4u,&error)==FG_OK;clock_gettime(CLOCK_MONOTONIC,&start);ok=ok&&fg_vk_profile_begin(context,&error)==FG_OK&&fg_vk_begin(context,&error)==FG_OK;for(uint32_t i=0;ok&&i<ITERATIONS;i++)ok=fg_vk_gdn_recurrent_decode(context,gor,gsr,gq,gz,ga,gb,gal,gdt,gn,VALUE_HEADS,KEY_HEADS,DIM,1e-6f,&error)==FG_OK;if(ok)ok=fg_vk_end(context,&error)==FG_OK&&fg_vk_profile_end(context,&old_profile,&error)==FG_OK;clock_gettime(CLOCK_MONOTONIC,&end);double old_wall=((double)(end.tv_sec-start.tv_sec)*1e3+(double)(end.tv_nsec-start.tv_nsec)*1e-6)/(double)ITERATIONS;ok=ok&&fg_vk_tensor_write(gsc,0,initial,STATE_VALUES*4u,&error)==FG_OK;clock_gettime(CLOCK_MONOTONIC,&start);ok=ok&&fg_vk_profile_begin(context,&error)==FG_OK&&fg_vk_begin(context,&error)==FG_OK;for(uint32_t i=0;ok&&i<ITERATIONS;i++)ok=fg_vk_gdn_recurrent_algebraic(context,goc,gsc,gq,gz,ga,gb,gal,gdt,gn,VALUE_HEADS,KEY_HEADS,DIM,1e-6f,&error)==FG_OK;if(ok)ok=fg_vk_end(context,&error)==FG_OK&&fg_vk_profile_end(context,&new_profile,&error)==FG_OK;clock_gettime(CLOCK_MONOTONIC,&end);double new_wall=((double)(end.tv_sec-start.tv_sec)*1e3+(double)(end.tv_nsec-start.tv_nsec)*1e-6)/(double)ITERATIONS;if(ok)fprintf(stderr,"GDN_ALGEBRAIC_BENCH iterations=%u old_gpu_us=%.3f new_gpu_us=%.3f old_wall_us=%.3f new_wall_us=%.3f\n",ITERATIONS,old_profile.gpu_ms*1000.0/(double)ITERATIONS,new_profile.gpu_ms*1000.0/(double)ITERATIONS,old_wall*1000.0,new_wall*1000.0);}
    fg_vk_tensor_destroy(goc);fg_vk_tensor_destroy(gor);fg_vk_tensor_destroy(gsc);fg_vk_tensor_destroy(gsr);fg_vk_tensor_destroy(gn);fg_vk_tensor_destroy(gdt);fg_vk_tensor_destroy(gal);fg_vk_tensor_destroy(gb);fg_vk_tensor_destroy(ga);fg_vk_tensor_destroy(gz);fg_vk_tensor_destroy(gq);free(candidate);free(reference);free(state_candidate);free(state_reference);free(initial);free(z);free(qkv);return ok;
}

static int test_gdn_prefill_scan(void){
    enum{TOKENS=3,CHANNELS=257,VALUE_HEADS=2,KEY_HEADS=1,DIM=128,KEY_WIDTH=KEY_HEADS*DIM,VALUE_WIDTH=VALUE_HEADS*DIM,QKV_WIDTH=2*KEY_WIDTH+VALUE_WIDTH,STATE_VALUES=VALUE_HEADS*DIM*DIM};
    float *projection=malloc(TOKENS*CHANNELS*4u),*conv_weight=malloc(CHANNELS*4u*4u),*conv_initial=malloc(CHANNELS*4u*4u),*conv_sequential=malloc(CHANNELS*4u*4u),*conv_batched=malloc(CHANNELS*4u*4u),*conv_output_sequential=malloc(TOKENS*CHANNELS*4u),*conv_output_batched=malloc(TOKENS*CHANNELS*4u);if(!projection||!conv_weight||!conv_initial||!conv_sequential||!conv_batched||!conv_output_sequential||!conv_output_batched)return 0;
    for(uint32_t i=0;i<TOKENS*CHANNELS;i++)projection[i]=sinf((float)i*0.017f);
    for(uint32_t i=0;i<CHANNELS*4u;i++){conv_weight[i]=cosf((float)i*0.013f)*0.25f;conv_initial[i]=sinf((float)i*0.011f)*0.1f;}
    fg_vk_tensor *gp=tensor(projection,TOKENS*CHANNELS*4u),*gcw=tensor(conv_weight,CHANNELS*16u),*gcs=tensor(conv_initial,CHANNELS*16u),*gcb=tensor(conv_initial,CHANNELS*16u),*gso=tensor(NULL,TOKENS*CHANNELS*4u),*gbo=tensor(NULL,TOKENS*CHANNELS*4u);int ok=gp&&gcw&&gcs&&gcb&&gso&&gbo;
    for(uint32_t token=0;ok&&token<TOKENS;token++){fg_vk_tensor *pv=NULL,*ov=NULL;ok=fg_vk_tensor_view(gp,(uint64_t)token*CHANNELS*4u,CHANNELS*4u,&pv,&error)==FG_OK&&fg_vk_tensor_view(gso,(uint64_t)token*CHANNELS*4u,CHANNELS*4u,&ov,&error)==FG_OK&&fg_vk_gdn_conv_decode(context,ov,gcs,pv,gcw,CHANNELS,&error)==FG_OK;fg_vk_tensor_destroy(ov);fg_vk_tensor_destroy(pv);}if(ok)ok=fg_vk_gdn_conv_prefill(context,gbo,gcb,gp,gcw,CHANNELS,TOKENS,&error)==FG_OK&&fg_vk_tensor_read(gso,0,conv_output_sequential,TOKENS*CHANNELS*4u,&error)==FG_OK&&fg_vk_tensor_read(gbo,0,conv_output_batched,TOKENS*CHANNELS*4u,&error)==FG_OK&&fg_vk_tensor_read(gcs,0,conv_sequential,CHANNELS*16u,&error)==FG_OK&&fg_vk_tensor_read(gcb,0,conv_batched,CHANNELS*16u,&error)==FG_OK;for(uint32_t i=0;ok&&i<TOKENS*CHANNELS;i++)if(conv_output_sequential[i]!=conv_output_batched[i])ok=0;for(uint32_t i=0;ok&&i<CHANNELS*4u;i++)if(conv_sequential[i]!=conv_batched[i])ok=0;
    float *qkv=malloc(TOKENS*QKV_WIDTH*4u),*z=malloc(TOKENS*VALUE_WIDTH*4u),alpha[TOKENS*VALUE_HEADS],beta[TOKENS*VALUE_HEADS],a_decay[VALUE_HEADS],dt[VALUE_HEADS],norm[DIM],*state_initial=malloc(STATE_VALUES*4u),*state_sequential=malloc(STATE_VALUES*4u),*state_batched=malloc(STATE_VALUES*4u),*output_sequential=malloc(TOKENS*VALUE_WIDTH*4u),*output_batched=malloc(TOKENS*VALUE_WIDTH*4u);if(!qkv||!z||!state_initial||!state_sequential||!state_batched||!output_sequential||!output_batched)ok=0;
    for(uint32_t i=0;ok&&i<TOKENS*QKV_WIDTH;i++)qkv[i]=sinf((float)i*0.007f)+0.1f*cosf((float)i*0.019f);
    for(uint32_t i=0;ok&&i<TOKENS*VALUE_WIDTH;i++)z[i]=cosf((float)i*0.009f);
    for(uint32_t token=0;ok&&token<TOKENS;token++)for(uint32_t head=0;head<VALUE_HEADS;head++){alpha[token*VALUE_HEADS+head]=-0.2f+(float)(token+head)*0.1f;beta[token*VALUE_HEADS+head]=0.3f-(float)(token+head)*0.07f;}
    for(uint32_t head=0;ok&&head<VALUE_HEADS;head++){a_decay[head]=-0.03f*(float)(head+1u);dt[head]=-0.1f+(float)head*0.02f;}
    for(uint32_t i=0;ok&&i<DIM;i++)norm[i]=0.8f+0.1f*sinf((float)i*0.03f);
    for(uint32_t i=0;ok&&i<STATE_VALUES;i++)state_initial[i]=sinf((float)i*0.0007f)*0.01f;
    fg_vk_tensor *gq=ok?tensor(qkv,TOKENS*QKV_WIDTH*4u):NULL,*gz=ok?tensor(z,TOKENS*VALUE_WIDTH*4u):NULL,*ga=ok?tensor(alpha,sizeof(alpha)):NULL,*gb=ok?tensor(beta,sizeof(beta)):NULL,*gad=ok?tensor(a_decay,sizeof(a_decay)):NULL,*gdt=ok?tensor(dt,sizeof(dt)):NULL,*gn=ok?tensor(norm,sizeof(norm)):NULL,*gss=ok?tensor(state_initial,STATE_VALUES*4u):NULL,*gsb=ok?tensor(state_initial,STATE_VALUES*4u):NULL,*gos=ok?tensor(NULL,TOKENS*VALUE_WIDTH*4u):NULL,*gob=ok?tensor(NULL,TOKENS*VALUE_WIDTH*4u):NULL;ok=ok&&gq&&gz&&ga&&gb&&gad&&gdt&&gn&&gss&&gsb&&gos&&gob;
    for(uint32_t token=0;ok&&token<TOKENS;token++){fg_vk_tensor *qv=NULL,*zv=NULL,*av=NULL,*bv=NULL,*ov=NULL;ok=fg_vk_tensor_view(gq,(uint64_t)token*QKV_WIDTH*4u,QKV_WIDTH*4u,&qv,&error)==FG_OK&&fg_vk_tensor_view(gz,(uint64_t)token*VALUE_WIDTH*4u,VALUE_WIDTH*4u,&zv,&error)==FG_OK&&fg_vk_tensor_view(ga,(uint64_t)token*VALUE_HEADS*4u,VALUE_HEADS*4u,&av,&error)==FG_OK&&fg_vk_tensor_view(gb,(uint64_t)token*VALUE_HEADS*4u,VALUE_HEADS*4u,&bv,&error)==FG_OK&&fg_vk_tensor_view(gos,(uint64_t)token*VALUE_WIDTH*4u,VALUE_WIDTH*4u,&ov,&error)==FG_OK&&fg_vk_gdn_recurrent_decode(context,ov,gss,qv,zv,av,bv,gad,gdt,gn,VALUE_HEADS,KEY_HEADS,DIM,1e-6f,&error)==FG_OK;fg_vk_tensor_destroy(ov);fg_vk_tensor_destroy(bv);fg_vk_tensor_destroy(av);fg_vk_tensor_destroy(zv);fg_vk_tensor_destroy(qv);}if(ok)ok=fg_vk_gdn_recurrent_prefill(context,gob,gsb,gq,gz,ga,gb,gad,gdt,gn,VALUE_HEADS,KEY_HEADS,DIM,TOKENS,1e-6f,&error)==FG_OK&&fg_vk_tensor_read(gos,0,output_sequential,TOKENS*VALUE_WIDTH*4u,&error)==FG_OK&&fg_vk_tensor_read(gob,0,output_batched,TOKENS*VALUE_WIDTH*4u,&error)==FG_OK&&fg_vk_tensor_read(gss,0,state_sequential,STATE_VALUES*4u,&error)==FG_OK&&fg_vk_tensor_read(gsb,0,state_batched,STATE_VALUES*4u,&error)==FG_OK;for(uint32_t i=0;ok&&i<TOKENS*VALUE_WIDTH;i++)if(fabsf(output_sequential[i]-output_batched[i])>2e-6f)ok=0;for(uint32_t i=0;ok&&i<STATE_VALUES;i++)if(fabsf(state_sequential[i]-state_batched[i])>2e-7f)ok=0;
    fg_vk_tensor_destroy(gob);fg_vk_tensor_destroy(gos);fg_vk_tensor_destroy(gsb);fg_vk_tensor_destroy(gss);fg_vk_tensor_destroy(gn);fg_vk_tensor_destroy(gdt);fg_vk_tensor_destroy(gad);fg_vk_tensor_destroy(gb);fg_vk_tensor_destroy(ga);fg_vk_tensor_destroy(gz);fg_vk_tensor_destroy(gq);free(output_batched);free(output_sequential);free(state_batched);free(state_sequential);free(state_initial);free(z);free(qkv);fg_vk_tensor_destroy(gbo);fg_vk_tensor_destroy(gso);fg_vk_tensor_destroy(gcb);fg_vk_tensor_destroy(gcs);fg_vk_tensor_destroy(gcw);fg_vk_tensor_destroy(gp);free(conv_output_batched);free(conv_output_sequential);free(conv_batched);free(conv_sequential);free(conv_initial);free(conv_weight);free(projection);return ok;
}

static int test_iq4_nl_dequant(void){
    enum{ROWS=16,WIDTH=160,ROW_BYTES=90};uint8_t packed[ROWS*ROW_BYTES];float expected[ROWS*WIDTH],got[ROWS*WIDTH];memset(packed,0,sizeof(packed));for(uint32_t row=0;row<ROWS;row++)for(uint32_t block=0;block<WIDTH/32u;block++){uint8_t *p=packed+row*ROW_BYTES+block*18u;uint16_t d=fg_f32_to_f16(0.00390625f*(float)(row+block+1u));memcpy(p,&d,2u);for(uint32_t i=0;i<16u;i++)p[2u+i]=(uint8_t)(((i+row)&15u)|(((15u-i+block)&15u)<<4u));}fg_dequantize_iq4_nl(packed,expected,ROWS*WIDTH);fg_vk_tensor *input=tensor(packed,sizeof(packed)),*output=tensor(NULL,sizeof(got));int ok=input&&output&&fg_vk_dequantize_iq4_nl(context,output,input,ROWS,WIDTH,&error)==FG_OK&&fg_vk_tensor_read(output,0,got,sizeof(got),&error)==FG_OK;for(uint32_t i=0;ok&&i<ROWS*WIDTH;i++)if(got[i]!=expected[i]){fprintf(stderr,"IQ4_NL %u GPU=%g CPU=%g\n",i,got[i],expected[i]);ok=0;}fg_vk_tensor_destroy(output);fg_vk_tensor_destroy(input);return ok;
}

static int test_ngram_direct_lookup(void){
    const uint64_t table_bytes=UINT64_C(320001536)*FG_NGRAM_ROW_BYTES;char path[128];snprintf(path,sizeof(path),"/tmp/fg-ngram-%ld.iq4nl",(long)getpid());unlink(path);int fd=open(path,O_CREAT|O_EXCL|O_RDWR|O_CLOEXEC,0600);if(fd<0)return 0;int ok=ftruncate(fd,(off_t)fg_align_up_u64(table_bytes,FG_ALIGNMENT))==0;const int32_t history[]={10,20,30};uint64_t rows[FG_NGRAM_HEAD_COUNT],addresses[FG_NGRAM_HEAD_COUNT];uint8_t packed[FG_NGRAM_HEAD_COUNT*FG_NGRAM_ROW_BYTES];float expected[FG_NGRAM_HEAD_COUNT*FG_NGRAM_EMBED_WIDTH],got[FG_NGRAM_HEAD_COUNT*FG_NGRAM_EMBED_WIDTH];if(ok)ok=fg_q38_ngram_lookup(history,3,rows,addresses,&error)==FG_OK;for(uint32_t row=0;ok&&row<FG_NGRAM_HEAD_COUNT;row++){uint8_t *p=packed+row*FG_NGRAM_ROW_BYTES;for(uint32_t block=0;block<FG_NGRAM_EMBED_WIDTH/32u;block++){uint8_t *b=p+block*18u;uint16_t d=fg_f32_to_f16((float)(row+1u)*0.001953125f);memcpy(b,&d,2u);for(uint32_t i=0;i<16u;i++)b[2u+i]=(uint8_t)(((i+row)&15u)|(((i+block+3u)&15u)<<4u));}ok=pwrite(fd,p,FG_NGRAM_ROW_BYTES,(off_t)addresses[row])==FG_NGRAM_ROW_BYTES;}close(fd);fg_dequantize_iq4_nl(packed,expected,FG_NGRAM_HEAD_COUNT*FG_NGRAM_EMBED_WIDTH);fg_ngram_store *store=NULL;fg_vk_tensor *embedding=NULL;if(ok)ok=fg_ngram_store_open(&store,context,path,table_bytes,&error)==FG_OK;if(ok)ok=fg_ngram_store_lookup(store,history,3,&embedding,&error)==FG_OK;if(ok)ok=fg_vk_tensor_read(embedding,0,got,sizeof(got),&error)==FG_OK;for(uint32_t i=0;ok&&i<FG_NGRAM_HEAD_COUNT*FG_NGRAM_EMBED_WIDTH;i++)if(got[i]!=expected[i]){fprintf(stderr,"n-gram lookup %u GPU=%g CPU=%g\n",i,got[i],expected[i]);ok=0;}fg_ngram_store_close(store);unlink(path);return ok;
}

static int test_ngram_prefill_lookup(void){
    const uint64_t table_bytes=UINT64_C(320001536)*FG_NGRAM_ROW_BYTES;char path[128];snprintf(path,sizeof(path),"/tmp/fg-ngram-prefill-%ld.iq4nl",(long)getpid());unlink(path);int fd=open(path,O_CREAT|O_EXCL|O_RDWR|O_CLOEXEC,0600);if(fd<0)return 0;int ok=ftruncate(fd,(off_t)fg_align_up_u64(table_bytes,FG_ALIGNMENT))==0;const int32_t history[]={100,200,300,400,500};enum{FIRST=1,TOKENS=3};uint64_t addresses[TOKENS*FG_NGRAM_HEAD_COUNT],rows[TOKENS*FG_NGRAM_HEAD_COUNT];uint8_t packed[sizeof(addresses)/sizeof(addresses[0])*FG_NGRAM_ROW_BYTES];float expected[sizeof(addresses)/sizeof(addresses[0])*FG_NGRAM_EMBED_WIDTH],got[sizeof(expected)/sizeof(expected[0])];
    for(uint32_t token=0;ok&&token<TOKENS;token++)ok=fg_q38_ngram_lookup(history,FIRST+token+1u,rows+(uint64_t)token*FG_NGRAM_HEAD_COUNT,addresses+(uint64_t)token*FG_NGRAM_HEAD_COUNT,&error)==FG_OK;
    for(uint32_t i=0;ok&&i<TOKENS*FG_NGRAM_HEAD_COUNT;i++){uint8_t row[FG_NGRAM_ROW_BYTES];uint64_t row_id=addresses[i]/FG_NGRAM_ROW_BYTES;for(uint32_t block=0;block<FG_NGRAM_EMBED_WIDTH/32u;block++){uint8_t *b=row+block*18u;uint16_t d=fg_f32_to_f16(0.001f+(float)(row_id%17u)*0.0001f);memcpy(b,&d,2u);for(uint32_t x=0;x<16u;x++)b[2u+x]=(uint8_t)(((row_id+block+x)&15u)|(((row_id+block*3u+x)&15u)<<4u));}memcpy(packed+(uint64_t)i*FG_NGRAM_ROW_BYTES,row,sizeof(row));ok=pwrite(fd,row,FG_NGRAM_ROW_BYTES,(off_t)addresses[i])==FG_NGRAM_ROW_BYTES;}
    close(fd);fg_dequantize_iq4_nl(packed,expected,TOKENS*FG_NGRAM_HEAD_COUNT*FG_NGRAM_EMBED_WIDTH);fg_ngram_store *store=NULL;fg_vk_tensor *embedding=NULL;if(ok)ok=fg_ngram_store_open(&store,context,path,table_bytes,&error)==FG_OK;if(ok)ok=fg_ngram_store_lookup_prefill(store,history,sizeof(history)/sizeof(history[0]),FIRST,TOKENS,&embedding,&error)==FG_OK&&fg_vk_tensor_bytes(embedding)==(uint64_t)TOKENS*FG_NGRAM_HEAD_COUNT*FG_NGRAM_EMBED_WIDTH*4u;if(ok)ok=fg_vk_tensor_read(embedding,0,got,sizeof(got),&error)==FG_OK;for(uint32_t i=0;ok&&i<TOKENS*FG_NGRAM_HEAD_COUNT*FG_NGRAM_EMBED_WIDTH;i++)if(got[i]!=expected[i]){fprintf(stderr,"n-gram prefill lookup %u GPU=%g CPU=%g\n",i,got[i],expected[i]);ok=0;}
    if(ok){fg_vk_tensor *single=NULL;ok=fg_ngram_store_lookup(store,history,4u,&single,&error)==FG_OK;float one[FG_NGRAM_HEAD_COUNT*FG_NGRAM_EMBED_WIDTH];if(ok)ok=fg_vk_tensor_read(single,0,one,sizeof(one),&error)==FG_OK;for(uint32_t i=0;ok&&i<FG_NGRAM_HEAD_COUNT*FG_NGRAM_EMBED_WIDTH;i++)if(one[i]!=got[2u*FG_NGRAM_HEAD_COUNT*FG_NGRAM_EMBED_WIDTH+i])ok=0;}
    fg_ngram_store_close(store);unlink(path);return ok;
}

static int test_ple_decode(void){
    enum{HIDDEN=2560,GROUPS=4,HYPER=10240,HISTORY=9};float *key=malloc(HYPER*4u),*query=malloc(HYPER*4u),*value=malloc(HIDDEN*4u),*gated=malloc(HYPER*4u),*normalized=malloc(HYPER*4u),*weight=malloc(HYPER*4u*4u),*state=malloc(HYPER*HISTORY*4u),*state_expected=malloc(HYPER*HISTORY*4u),*ple_expected=malloc(HYPER*4u),*got=malloc(HYPER*4u),*left=malloc(HYPER*4u),*sum_expected=malloc(HYPER*4u);if(!key||!query||!value||!gated||!normalized||!weight||!state||!state_expected||!ple_expected||!got||!left||!sum_expected)return 0;for(uint32_t i=0;i<HYPER;i++){key[i]=sinf((float)i*0.0021f);query[i]=cosf((float)i*0.0017f);normalized[i]=sinf((float)i*0.0031f)*0.5f;left[i]=cosf((float)i*0.0043f);for(uint32_t k=0;k<4u;k++)weight[i*4u+k]=0.1f*cosf((float)(i*4u+k)*0.0013f);for(uint32_t h=0;h<HISTORY;h++)state[i*HISTORY+h]=0.03f*sinf((float)(i*HISTORY+h)*0.0007f);}for(uint32_t i=0;i<HIDDEN;i++)value[i]=cosf((float)i*0.0053f);memcpy(state_expected,state,HYPER*HISTORY*4u);for(uint32_t group=0;group<GROUPS;group++){float dot=0.0f;for(uint32_t i=0;i<HIDDEN;i++)dot=fmaf(key[group*HIDDEN+i],query[group*HIDDEN+i],dot);float gate=dot/sqrtf((float)HIDDEN);gate=copysignf(sqrtf(fmaxf(fabsf(gate),1e-6f)),gate);float scale=1.0f/(1.0f+expf(-gate));for(uint32_t i=0;i<HIDDEN;i++)gated[group*HIDDEN+i]=scale*value[i];}for(uint32_t i=0;i<HYPER;i++){uint32_t base=i*HISTORY;float conv=weight[i*4u]*state_expected[base]+weight[i*4u+1u]*state_expected[base+3u]+weight[i*4u+2u]*state_expected[base+6u]+weight[i*4u+3u]*normalized[i];for(uint32_t h=0;h<8u;h++)state_expected[base+h]=state_expected[base+h+1u];state_expected[base+8u]=normalized[i];ple_expected[i]=gated[i]+conv/(1.0f+expf(-conv));sum_expected[i]=left[i]+ple_expected[i];}
    fg_vk_tensor *gk=tensor(key,HYPER*4u),*gq=tensor(query,HYPER*4u),*gv=tensor(value,HIDDEN*4u),*gg=tensor(NULL,HYPER*4u),*gn=tensor(normalized,HYPER*4u),*gw=tensor(weight,HYPER*16u),*gs=tensor(state,HYPER*HISTORY*4u),*go=tensor(NULL,HYPER*4u),*gl=tensor(left,HYPER*4u),*ga=tensor(NULL,HYPER*4u);int ok=gk&&gq&&gv&&gg&&gn&&gw&&gs&&go&&gl&&ga&&fg_vk_ple_gate(context,gg,gk,gq,gv,&error)==FG_OK&&fg_vk_tensor_read(gg,0,got,HYPER*4u,&error)==FG_OK;for(uint32_t i=0;ok&&i<HYPER;i++)if(fabsf(got[i]-gated[i])>2e-5f){fprintf(stderr,"PLE gate %u GPU=%g CPU=%g\n",i,got[i],gated[i]);ok=0;}if(ok)ok=fg_vk_ple_conv_decode(context,go,gs,gg,gn,gw,&error)==FG_OK&&fg_vk_tensor_read(go,0,got,HYPER*4u,&error)==FG_OK&&fg_vk_tensor_read(gs,0,state,HYPER*HISTORY*4u,&error)==FG_OK;for(uint32_t i=0;ok&&i<HYPER;i++)if(fabsf(got[i]-ple_expected[i])>2e-5f){fprintf(stderr,"PLE conv %u GPU=%g CPU=%g\n",i,got[i],ple_expected[i]);ok=0;}for(uint32_t i=0;ok&&i<HYPER*HISTORY;i+=37u)if(state[i]!=state_expected[i]){fprintf(stderr,"PLE state %u GPU=%g CPU=%g\n",i,state[i],state_expected[i]);ok=0;}if(ok)ok=fg_vk_add_f32(context,ga,gl,go,HYPER,&error)==FG_OK&&fg_vk_tensor_read(ga,0,got,HYPER*4u,&error)==FG_OK;for(uint32_t i=0;ok&&i<HYPER;i++)if(fabsf(got[i]-sum_expected[i])>2e-5f){fprintf(stderr,"PLE add %u GPU=%g CPU=%g\n",i,got[i],sum_expected[i]);ok=0;}fg_vk_tensor_destroy(ga);fg_vk_tensor_destroy(gl);fg_vk_tensor_destroy(go);fg_vk_tensor_destroy(gs);fg_vk_tensor_destroy(gw);fg_vk_tensor_destroy(gn);fg_vk_tensor_destroy(gg);fg_vk_tensor_destroy(gv);fg_vk_tensor_destroy(gq);fg_vk_tensor_destroy(gk);free(sum_expected);free(left);free(got);free(ple_expected);free(state_expected);free(state);free(weight);free(normalized);free(gated);free(value);free(query);free(key);return ok;
}

static int test_ple_prefill_scan(void){
    enum{TOKENS=3,HIDDEN=2560,HYPER=10240,HISTORY=9};float *key=malloc(TOKENS*HYPER*4u),*query=malloc(TOKENS*HYPER*4u),*value=malloc(TOKENS*HIDDEN*4u),*normalized=malloc(TOKENS*HYPER*4u),*weight=malloc(HYPER*4u*4u),*state_initial=malloc(HYPER*HISTORY*4u),*gate_sequential=malloc(TOKENS*HYPER*4u),*gate_batched=malloc(TOKENS*HYPER*4u),*conv_sequential=malloc(TOKENS*HYPER*4u),*conv_batched=malloc(TOKENS*HYPER*4u),*state_sequential=malloc(HYPER*HISTORY*4u),*state_batched=malloc(HYPER*HISTORY*4u);if(!key||!query||!value||!normalized||!weight||!state_initial||!gate_sequential||!gate_batched||!conv_sequential||!conv_batched||!state_sequential||!state_batched)return 0;
    for(uint32_t i=0;i<TOKENS*HYPER;i++){key[i]=sinf((float)i*0.003f);query[i]=cosf((float)i*0.004f);normalized[i]=sinf((float)i*0.005f)*0.5f;}for(uint32_t i=0;i<TOKENS*HIDDEN;i++)value[i]=cosf((float)i*0.007f);for(uint32_t i=0;i<HYPER*4u;i++)weight[i]=0.1f*cosf((float)i*0.0011f);for(uint32_t i=0;i<HYPER*HISTORY;i++)state_initial[i]=0.02f*sinf((float)i*0.0003f);
    fg_vk_tensor *gk=tensor(key,TOKENS*HYPER*4u),*gq=tensor(query,TOKENS*HYPER*4u),*gv=tensor(value,TOKENS*HIDDEN*4u),*gn=tensor(normalized,TOKENS*HYPER*4u),*gw=tensor(weight,HYPER*16u),*gss=tensor(state_initial,HYPER*HISTORY*4u),*gsb=tensor(state_initial,HYPER*HISTORY*4u),*ggs=tensor(NULL,TOKENS*HYPER*4u),*ggb=tensor(NULL,TOKENS*HYPER*4u),*gos=tensor(NULL,TOKENS*HYPER*4u),*gob=tensor(NULL,TOKENS*HYPER*4u);int ok=gk&&gq&&gv&&gn&&gw&&gss&&gsb&&ggs&&ggb&&gos&&gob;
    for(uint32_t token=0;ok&&token<TOKENS;token++){fg_vk_tensor *kv=NULL,*qv=NULL,*vv=NULL,*ov=NULL;ok=fg_vk_tensor_view(gk,(uint64_t)token*HYPER*4u,HYPER*4u,&kv,&error)==FG_OK&&fg_vk_tensor_view(gq,(uint64_t)token*HYPER*4u,HYPER*4u,&qv,&error)==FG_OK&&fg_vk_tensor_view(gv,(uint64_t)token*HIDDEN*4u,HIDDEN*4u,&vv,&error)==FG_OK&&fg_vk_tensor_view(ggs,(uint64_t)token*HYPER*4u,HYPER*4u,&ov,&error)==FG_OK&&fg_vk_ple_gate(context,ov,kv,qv,vv,&error)==FG_OK;fg_vk_tensor_destroy(ov);fg_vk_tensor_destroy(vv);fg_vk_tensor_destroy(qv);fg_vk_tensor_destroy(kv);}if(ok)ok=fg_vk_ple_gate_prefill(context,ggb,gk,gq,gv,TOKENS,&error)==FG_OK&&fg_vk_tensor_read(ggs,0,gate_sequential,TOKENS*HYPER*4u,&error)==FG_OK&&fg_vk_tensor_read(ggb,0,gate_batched,TOKENS*HYPER*4u,&error)==FG_OK;for(uint32_t i=0;ok&&i<TOKENS*HYPER;i++)if(gate_sequential[i]!=gate_batched[i])ok=0;
    for(uint32_t token=0;ok&&token<TOKENS;token++){fg_vk_tensor *gvw=NULL,*nv=NULL,*ov=NULL;ok=fg_vk_tensor_view(ggs,(uint64_t)token*HYPER*4u,HYPER*4u,&gvw,&error)==FG_OK&&fg_vk_tensor_view(gn,(uint64_t)token*HYPER*4u,HYPER*4u,&nv,&error)==FG_OK&&fg_vk_tensor_view(gos,(uint64_t)token*HYPER*4u,HYPER*4u,&ov,&error)==FG_OK&&fg_vk_ple_conv_decode(context,ov,gss,gvw,nv,gw,&error)==FG_OK;fg_vk_tensor_destroy(ov);fg_vk_tensor_destroy(nv);fg_vk_tensor_destroy(gvw);}if(ok)ok=fg_vk_ple_conv_prefill(context,gob,gsb,ggb,gn,gw,TOKENS,&error)==FG_OK&&fg_vk_tensor_read(gos,0,conv_sequential,TOKENS*HYPER*4u,&error)==FG_OK&&fg_vk_tensor_read(gob,0,conv_batched,TOKENS*HYPER*4u,&error)==FG_OK&&fg_vk_tensor_read(gss,0,state_sequential,HYPER*HISTORY*4u,&error)==FG_OK&&fg_vk_tensor_read(gsb,0,state_batched,HYPER*HISTORY*4u,&error)==FG_OK;for(uint32_t i=0;ok&&i<TOKENS*HYPER;i++)if(conv_sequential[i]!=conv_batched[i])ok=0;for(uint32_t i=0;ok&&i<HYPER*HISTORY;i++)if(state_sequential[i]!=state_batched[i])ok=0;
    fg_vk_tensor_destroy(gob);fg_vk_tensor_destroy(gos);fg_vk_tensor_destroy(ggb);fg_vk_tensor_destroy(ggs);fg_vk_tensor_destroy(gsb);fg_vk_tensor_destroy(gss);fg_vk_tensor_destroy(gw);fg_vk_tensor_destroy(gn);fg_vk_tensor_destroy(gv);fg_vk_tensor_destroy(gq);fg_vk_tensor_destroy(gk);free(state_batched);free(state_sequential);free(conv_batched);free(conv_sequential);free(gate_batched);free(gate_sequential);free(state_initial);free(weight);free(normalized);free(value);free(query);free(key);return ok;
}

static const fg_vk_profile_kernel *find_profile_kernel(const fg_vk_profile *profile,const char *scope,const char *name){for(uint32_t i=0;i<profile->kernel_count;i++)if(strcmp(profile->kernels[i].scope,scope)==0&&strcmp(profile->kernels[i].name,name)==0)return &profile->kernels[i];return NULL;}
static int test_gpu_profile(void){
    enum{VALUES=256};float left[VALUES],right[VALUES];for(uint32_t i=0;i<VALUES;i++){left[i]=sinf((float)i*0.031f);right[i]=cosf((float)i*0.017f);}fg_vk_tensor *l=tensor(left,sizeof(left)),*r=tensor(right,sizeof(right)),*sum=tensor(NULL,sizeof(left)),*out=tensor(NULL,sizeof(left));fg_vk_profile profile={0};fg_vk_counters before={0},after={0};fg_vk_get_counters(context,&before);int ok=l&&r&&sum&&out&&!fg_vk_batch_active(context)&&!fg_vk_profile_active(context)&&fg_vk_profile_begin(context,&error)==FG_OK&&fg_vk_profile_active(context)&&fg_vk_begin(context,&error)==FG_OK&&fg_vk_begin(context,&error)==FG_OK&&fg_vk_batch_active(context)&&fg_vk_profile_set_scope(context,"sum",&error)==FG_OK&&fg_vk_add_f32(context,sum,l,r,VALUES,&error)==FG_OK&&fg_vk_end(context,&error)==FG_OK&&fg_vk_batch_active(context)&&fg_vk_profile_set_scope(context,"activation",&error)==FG_OK&&fg_vk_silu_scaled(context,out,sum,VALUES,1.0f,&error)==FG_OK&&fg_vk_end(context,&error)==FG_OK&&!fg_vk_batch_active(context)&&fg_vk_profile_end(context,&profile,&error)==FG_OK&&!fg_vk_profile_active(context);fg_vk_get_counters(context,&after);const fg_vk_profile_kernel *add=ok?find_profile_kernel(&profile,"sum","fg_add_f32.spv"):NULL,*silu=ok?find_profile_kernel(&profile,"activation","fg_silu_scaled.spv"):NULL;ok=ok&&after.submissions-before.submissions==2u&&after.dispatches-before.dispatches==2u&&profile.submissions==1u&&profile.dispatches==2u&&profile.gpu_ms>0.0&&profile.kernel_ms>0.0&&profile.gpu_ms>=profile.kernel_ms&&add&&add->invocations==1u&&add->gpu_ms>0.0&&silu&&silu->invocations==1u&&silu->gpu_ms>0.0;fg_vk_tensor_destroy(out);fg_vk_tensor_destroy(sum);fg_vk_tensor_destroy(r);fg_vk_tensor_destroy(l);return ok;
}

static int run_test(const char *name,int (*fn)(void)){fprintf(stderr,"  [%s] ... ",name);fflush(stderr);int ok=fn();fprintf(stderr,"%s\n",ok?"ok":"FAIL");return ok;}
static int run_test_i(const char *name,int (*fn)(int),int arg){fprintf(stderr,"  [%s(%d)] ... ",name,arg);fflush(stderr);int ok=fn(arg);fprintf(stderr,"%s\n",ok?"ok":"FAIL");return ok;}
int main(void){if(fg_vk_open(&context,&error)!=FG_OK){fprintf(stderr,"Vulkan unavailable: %s\n",error.message);return 77;}fprintf(stderr,"Flash Gordon Vulkan device: %s\n",fg_vk_device_name(context));int ok=1;
ok=run_test("gpu_profile",test_gpu_profile)&&ok;
ok=run_test("q8_dense",test_q8_dense)&&ok;
ok=run_test("q8_embedding",test_q8_embedding)&&ok;
ok=run_test("hc_finalize",test_hc_finalize)&&ok;
ok=run_test("q8_k_quant",test_q8_k_quant)&&ok;
ok=run_test("q4_0_bytes",test_q4_0_bytes)&&ok;
ok=run_test("iq4_nl_dequant",test_iq4_nl_dequant)&&ok;
ok=run_test("ngram_direct_lookup",test_ngram_direct_lookup)&&ok;
ok=run_test("ngram_prefill_lookup",test_ngram_prefill_lookup)&&ok;
ok=run_test("ple_decode",test_ple_decode)&&ok;
ok=run_test("ple_prefill_scan",test_ple_prefill_scan)&&ok;
ok=run_test("qsa_quant_and_bf16",test_qsa_quant_and_bf16)&&ok;
ok=run_test("qsa_record_commit",test_qsa_record_commit)&&ok;
ok=run_test("qsa_record_gather",test_qsa_record_gather)&&ok;
ok=run_test("swiglu",test_swiglu)&&ok;
ok=run_test("dense_f32_and_silu",test_dense_f32_and_silu)&&ok;
ok=run_test("group_norm",test_group_norm)&&ok;
ok=run_test("gr_mix",test_gr_mix)&&ok;
ok=run_test("hc_inject_partial",test_hc_inject_partial)&&ok;
ok=run_test("gr_batch",test_gr_batch)&&ok;
ok=run_test("q5_1_down",test_q5_1_down)&&ok;
ok=run_test("q8_0_down",test_q8_0_down)&&ok;
ok=run_test("moe_reduce",test_moe_reduce)&&ok;
ok=run_test_i("kquant",test_kquant,12)&&ok;
ok=run_test_i("kquant",test_kquant,13)&&ok;
ok=run_test_i("kquant_expert_major_batch",test_kquant_expert_major_batch,12)&&ok;
ok=run_test_i("kquant_expert_major_batch",test_kquant_expert_major_batch,13)&&ok;
ok=run_test("expert_graph_replay",test_expert_graph_replay)&&ok;
ok=run_test("gdn_decode",test_gdn_decode)&&ok;
ok=run_test("gdn_algebraic",test_gdn_algebraic)&&ok;
ok=run_test("gdn_prefill_scan",test_gdn_prefill_scan)&&ok;
ok=run_test("qsa_indexer",test_qsa_indexer)&&ok;
ok=run_test("output_topk",test_output_topk)&&ok;
ok=run_test("qsa_prefill_prepare",test_qsa_prefill_prepare)&&ok;
ok=run_test("qsa_attention_single",test_qsa_attention_single)&&ok;
ok=run_test("qsa_attention",test_qsa_attention)&&ok;
fg_vk_close(context);if(!ok){fprintf(stderr,"native Vulkan oracle failed: %s\n",error.message);return 1;}puts("Flash Gordon native Vulkan production-dimension oracles: PASS");return 0;}
