#include "fg_quant.h"
#include "fg_vk.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

enum { INPUT = 10240, OUTPUT = 320, SPLITS = 8, ITERATIONS = 24 };

static double elapsed_ms(struct timespec begin,struct timespec end){return(double)(end.tv_sec-begin.tv_sec)*1e3+(double)(end.tv_nsec-begin.tv_nsec)*1e-6;}

int main(void){
    fg_error error={0};fg_vk_context *context=NULL;fg_status status=fg_vk_open(&context,&error);if(status!=FG_OK){fprintf(stderr,"Vulkan unavailable: %s\n",error.message);return 77;}uint32_t blocks=INPUT/FG_QK8_0,source_row=blocks*FG_Q8_0_BLOCK_BYTES;uint64_t source_bytes=(uint64_t)OUTPUT*source_row,cooked_bytes=fg_q8_0_cooked_matrix_bytes(INPUT,OUTPUT);uint8_t *source=malloc((size_t)source_bytes),*cooked=malloc((size_t)cooked_bytes);float *input=malloc(INPUT*4u),*reference=malloc(OUTPUT*4u),*candidate=malloc(OUTPUT*4u);if(!source||!cooked||!input||!reference||!candidate){fprintf(stderr,"allocation failed\n");return 1;}for(uint32_t row=0;row<OUTPUT;row++)for(uint32_t block=0;block<blocks;block++){uint8_t *value=source+((uint64_t)row*blocks+block)*FG_Q8_0_BLOCK_BYTES;uint16_t delta=fg_f32_to_f16(0.001f+(float)((row+block)%7u)*0.0001f);memcpy(value,&delta,sizeof(delta));for(uint32_t i=0;i<FG_QK8_0;i++)value[2u+i]=(uint8_t)(row*17u+block*29u+i*11u);}for(uint32_t i=0;i<INPUT;i++)input[i]=sinf((float)(i+3u)*0.013f)+0.1f*cosf((float)i*0.007f);if(!fg_cook_q8_0_rows(source,cooked,cooked_bytes,INPUT,OUTPUT)){fprintf(stderr,"cook failed\n");return 1;}
    fg_vk_tensor *generic_weight=NULL,*cooked_weight=NULL,*activation=NULL,*generic_output=NULL,*split_output=NULL,*partials=NULL;status=fg_vk_tensor_create(context,source_bytes,&generic_weight,&error);if(status==FG_OK)status=fg_vk_tensor_create(context,cooked_bytes,&cooked_weight,&error);if(status==FG_OK)status=fg_vk_tensor_create(context,INPUT*4u,&activation,&error);if(status==FG_OK)status=fg_vk_tensor_create(context,OUTPUT*4u,&generic_output,&error);if(status==FG_OK)status=fg_vk_tensor_create(context,OUTPUT*4u,&split_output,&error);if(status==FG_OK)status=fg_vk_tensor_create(context,OUTPUT*SPLITS*4u,&partials,&error);if(status==FG_OK)status=fg_vk_tensor_write(generic_weight,0,source,source_bytes,&error);if(status==FG_OK)status=fg_vk_tensor_write(cooked_weight,0,cooked,cooked_bytes,&error);if(status==FG_OK)fg_vk_tensor_set_format(cooked_weight,FG_VK_TENSOR_FORMAT_Q8_0_COOKED);if(status==FG_OK)status=fg_vk_tensor_write(activation,0,input,INPUT*4u,&error);if(status==FG_OK)status=fg_vk_dense_q8_0_f32(context,generic_output,generic_weight,activation,INPUT,OUTPUT,1u,1.0f,&error);if(status==FG_OK)status=fg_vk_begin(context,&error);if(status==FG_OK)status=fg_vk_dense_q8_0_cooked_split(context,split_output,partials,cooked_weight,activation,INPUT,OUTPUT,1u,SPLITS,1.0f,&error);if(status==FG_OK)status=fg_vk_end(context,&error);if(status==FG_OK)status=fg_vk_tensor_read(generic_output,0,reference,OUTPUT*4u,&error);if(status==FG_OK)status=fg_vk_tensor_read(split_output,0,candidate,OUTPUT*4u,&error);double max_abs=0.0,max_rel=0.0;for(uint32_t i=0;status==FG_OK&&i<OUTPUT;i++){double difference=fabs((double)candidate[i]-reference[i]),relative=difference/fmax(1.0,fabs((double)reference[i]));if(difference>max_abs)max_abs=difference;if(relative>max_rel)max_rel=relative;if(relative>2e-4){fprintf(stderr,"parity failed row=%u generic=%g split=%g\n",i,reference[i],candidate[i]);status=FG_ERR_MISMATCH;}}
    fg_vk_profile generic_profile={0},split_profile={0};struct timespec begin,end;clock_gettime(CLOCK_MONOTONIC,&begin);if(status==FG_OK)status=fg_vk_profile_begin(context,&error);if(status==FG_OK)status=fg_vk_begin(context,&error);for(uint32_t i=0;status==FG_OK&&i<ITERATIONS;i++)status=fg_vk_dense_q8_0_f32(context,generic_output,generic_weight,activation,INPUT,OUTPUT,1u,1.0f,&error);if(status==FG_OK)status=fg_vk_end(context,&error);if(status==FG_OK)status=fg_vk_profile_end(context,&generic_profile,&error);clock_gettime(CLOCK_MONOTONIC,&end);double generic_wall=elapsed_ms(begin,end)/(double)ITERATIONS;clock_gettime(CLOCK_MONOTONIC,&begin);if(status==FG_OK)status=fg_vk_profile_begin(context,&error);if(status==FG_OK)status=fg_vk_begin(context,&error);for(uint32_t i=0;status==FG_OK&&i<ITERATIONS;i++)status=fg_vk_dense_q8_0_cooked_split(context,split_output,partials,cooked_weight,activation,INPUT,OUTPUT,1u,SPLITS,1.0f,&error);if(status==FG_OK)status=fg_vk_end(context,&error);if(status==FG_OK)status=fg_vk_profile_end(context,&split_profile,&error);clock_gettime(CLOCK_MONOTONIC,&end);double split_wall=elapsed_ms(begin,end)/(double)ITERATIONS;if(status==FG_OK)fprintf(stderr,"HC_DOWN_SPLIT_AB splits=%u iterations=%u generic_gpu_us=%.3f split_gpu_us=%.3f generic_wall_us=%.3f split_wall_us=%.3f speedup=%.4f max_abs=%.9g max_rel=%.9g parity=PASS\n",SPLITS,ITERATIONS,generic_profile.kernel_ms*1000.0/ITERATIONS,split_profile.kernel_ms*1000.0/ITERATIONS,generic_wall*1000.0,split_wall*1000.0,(generic_profile.kernel_ms/split_profile.kernel_ms),max_abs,max_rel);else fprintf(stderr,"HC-down split failed: %s\n",error.message);
    fg_vk_tensor_destroy(partials);fg_vk_tensor_destroy(split_output);fg_vk_tensor_destroy(generic_output);fg_vk_tensor_destroy(activation);fg_vk_tensor_destroy(cooked_weight);fg_vk_tensor_destroy(generic_weight);fg_vk_close(context);free(candidate);free(reference);free(input);free(cooked);free(source);return status==FG_OK?0:1;
}