#version 460
layout(local_size_x=256,local_size_y=1,local_size_z=1)in;
layout(set=0,binding=0)readonly buffer Left{float left_value[];};
layout(set=0,binding=1)readonly buffer Right{float right_value[];};
layout(set=0,binding=2)writeonly buffer Output{float output_value[];};
layout(push_constant)uniform Push{uint values;}pc;
void main(){uint index=gl_GlobalInvocationID.x;if(index<pc.values)output_value[index]=left_value[index]+right_value[index];}
