#version 460
layout(local_size_x=256,local_size_y=1,local_size_z=1)in;
layout(set=0,binding=0)readonly buffer Reduced{float reduced_value[];};
layout(set=0,binding=1)readonly buffer Shared{float shared_value[];};
layout(set=0,binding=2)readonly buffer Scalar{float scalar_value[];};
layout(set=0,binding=3)writeonly buffer Output{float output_value[];};
layout(push_constant)uniform Push{uint values;}pc;
void main(){
    uint index=gl_GlobalInvocationID.x;
    if(index<pc.values)
        output_value[index]=reduced_value[index]+(1.0/(1.0+exp(-scalar_value[0])))*shared_value[index];
}
