#include "fg.h"
#include "fg_manifest.h"
#include "fg_pack.h"
#include "fg_runtime.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void usage(FILE *f){fprintf(f,"Flash Gordon %u.%u - Qwen3.8-Flash-Next BC250 appliance\n\nUsage:\n  flash-gordon pack --output DIR --source FILE [--source FILE ...] [--router-profile FILE] [--dry-run]\n  flash-gordon schema --source FILE [--source FILE ...]\n  flash-gordon rank --manifest FILE --rank N\n  flash-gordon serve --manifest FILE\n  flash-gordon bench --manifest FILE\n  flash-gordon eval --manifest FILE --prompt TEXT [--generate N]\n  flash-gordon inspect --manifest FILE\n",FG_VERSION_MAJOR,FG_VERSION_MINOR);}
static const char *arg_value(int *i,int argc,char **argv,const char *flag,fg_error *err){if(*i+1>=argc){fg_error_set(err,FG_ERR_ARGUMENT,"%s requires a value",flag);return NULL;}return argv[++*i];}
static fg_status pack_cmd(int argc,char **argv,fg_error *err){fg_pack_options o={0};const char **sources=calloc((size_t)argc,sizeof(*sources));if(!sources){fg_error_set(err,FG_ERR_OOM,"allocate source arguments");return FG_ERR_OOM;}for(int i=2;i<argc;i++){if(strcmp(argv[i],"--output")==0)o.output_dir=arg_value(&i,argc,argv,"--output",err);else if(strcmp(argv[i],"--source")==0)sources[o.source_count++]=arg_value(&i,argc,argv,"--source",err);else if(strcmp(argv[i],"--router-profile")==0)o.router_profile_path=arg_value(&i,argc,argv,"--router-profile",err);else if(strcmp(argv[i],"--dry-run")==0)o.dry_run=true;else{fg_error_set(err,FG_ERR_ARGUMENT,"unknown pack option: %s",argv[i]);free(sources);return FG_ERR_ARGUMENT;}if(err->code!=FG_OK){free(sources);return err->code;}}o.source_paths=sources;fg_status rc=fg_pack_run(&o,err);free(sources);return rc;}
static fg_status schema_cmd(int argc,char **argv,fg_error *err){const char **sources=calloc((size_t)argc,sizeof(*sources));uint32_t count=0;if(!sources){fg_error_set(err,FG_ERR_OOM,"allocate schema source arguments");return FG_ERR_OOM;}for(int i=2;i<argc;i++){if(strcmp(argv[i],"--source")==0)sources[count++]=arg_value(&i,argc,argv,"--source",err);else{fg_error_set(err,FG_ERR_ARGUMENT,"unknown schema option: %s",argv[i]);free(sources);return FG_ERR_ARGUMENT;}}fg_gguf g;fg_status rc=fg_gguf_open(sources,count,&g,err);if(rc==FG_OK){fg_gguf_print_schema(&g);fg_gguf_close(&g);}free(sources);return rc;}
static fg_status manifest_cmd(const char *cmd,int argc,char **argv,fg_error *err){const char *path=NULL,*prompt=NULL;uint32_t rank=UINT32_MAX,generate=1u;for(int i=2;i<argc;i++){if(strcmp(argv[i],"--manifest")==0)path=arg_value(&i,argc,argv,"--manifest",err);else if(strcmp(argv[i],"--rank")==0){const char *v=arg_value(&i,argc,argv,"--rank",err);if(v)rank=(uint32_t)strtoul(v,NULL,10);}else if(strcmp(argv[i],"--prompt")==0)prompt=arg_value(&i,argc,argv,"--prompt",err);else if(strcmp(argv[i],"--generate")==0){const char *v=arg_value(&i,argc,argv,"--generate",err);if(v)generate=(uint32_t)strtoul(v,NULL,10);}else{fg_error_set(err,FG_ERR_ARGUMENT,"unknown %s option: %s",cmd,argv[i]);return FG_ERR_ARGUMENT;}}if(!path){fg_error_set(err,FG_ERR_ARGUMENT,"%s requires --manifest",cmd);return FG_ERR_ARGUMENT;}if(strcmp(cmd,"rank")==0)return fg_rank_main(path,rank,err);if(strcmp(cmd,"serve")==0)return fg_serve_main(path,err);if(strcmp(cmd,"bench")==0)return fg_bench_main(path,err);if(strcmp(cmd,"eval")==0){if(!prompt){fg_error_set(err,FG_ERR_ARGUMENT,"eval requires --prompt");return FG_ERR_ARGUMENT;}return fg_eval_main(path,prompt,generate,err);}if(strcmp(cmd,"inspect")==0){fg_manifest *m=malloc(sizeof(*m));if(!m){fg_error_set(err,FG_ERR_OOM,"allocate manifest");return FG_ERR_OOM;}fg_status rc=fg_manifest_read(path,m,err);if(rc==FG_OK)fg_manifest_print(m);free(m);return rc;}return FG_ERR_ARGUMENT;}
int main(int argc,char **argv){fg_error err={0};if(argc<2||strcmp(argv[1],"--help")==0||strcmp(argv[1],"help")==0){usage(stdout);return 0;}fg_status rc;if(strcmp(argv[1],"pack")==0)rc=pack_cmd(argc,argv,&err);else if(strcmp(argv[1],"schema")==0)rc=schema_cmd(argc,argv,&err);else if(strcmp(argv[1],"rank")==0||strcmp(argv[1],"serve")==0||strcmp(argv[1],"bench")==0||strcmp(argv[1],"eval")==0||strcmp(argv[1],"inspect")==0)rc=manifest_cmd(argv[1],argc,argv,&err);else{usage(stderr);fprintf(stderr,"\nunknown command: %s\n",argv[1]);return FG_ERR_ARGUMENT;}if(rc!=FG_OK)fprintf(stderr,"flash-gordon: %s\n",err.message[0]?err.message:"operation failed");return (int)rc;}
