#include "fg_owner.h"
#include "fg_q38_math.h"
#include "fg_qsa.h"
#include "fg_topology.h"

#include <math.h>
#include <stdatomic.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

static double ts_ms(void){struct timespec t;clock_gettime(CLOCK_MONOTONIC,&t);return (double)t.tv_sec*1e3+(double)t.tv_nsec*1e-6;}

struct fg_owner_executor {
    fg_model *model;
    uint32_t max_tokens;
    bool replicated;
    fg_vk_tensor *hyper_norm,*low,*low_active,*up_logits,*inject_logits,*mixed,*injection,*hyper_output,*hyper_output_b;
    fg_vk_tensor *router_logits,*activation_q8k,*shared_gate,*shared_up,*shared_mid,*shared_output,*shared_scalar,*reduced;
    fg_vk_tensor *gdn_qkv,*gdn_conv_output,*gdn_z,*gdn_alpha,*gdn_beta,*gdn_core,*gdn_output;
    fg_vk_tensor *ple_key,*ple_value,*ple_key_norm,*ple_query_norm,*ple_gated,*ple_gated_norm,*ple_output,*ple_added,*ple_state;
    struct {fg_vk_tensor *conv_state,*recurrent_state;} gdn_state[FG_LAYER_COUNT];
    fg_qsa_session *qsa;
};

static fg_status scratch(fg_vk_context *vk,uint64_t values,fg_vk_tensor **out,fg_error *err){return fg_vk_tensor_create(vk,values*4u,out,err);}
fg_status fg_owner_executor_create(fg_owner_executor **out,fg_model *model,fg_error *err){
    if(!out||!model){fg_error_set(err,FG_ERR_ARGUMENT,"invalid owner executor arguments");return FG_ERR_ARGUMENT;}*out=NULL;
    fg_owner_executor *executor=calloc(1,sizeof(*executor));if(!executor){fg_error_set(err,FG_ERR_OOM,"allocate owner executor");return FG_ERR_OOM;}executor->model=model;fg_vk_context *vk=fg_model_vk(model);
    const fg_manifest *manifest=fg_model_manifest(model);executor->max_tokens=manifest->prefill_microbatch;if(!executor->max_tokens||executor->max_tokens>FG_PREFILL_MAX_TOKENS){fg_owner_executor_destroy(executor);fg_error_set(err,FG_ERR_MISMATCH,"manifest prefill microbatch exceeds owner executor limit");return FG_ERR_MISMATCH;}uint64_t tokens=executor->max_tokens;
    fg_status status=scratch(vk,10240u*tokens,&executor->hyper_norm,err);if(status==FG_OK)status=scratch(vk,320u*tokens,&executor->low,err);if(status==FG_OK)status=scratch(vk,320u*tokens,&executor->low_active,err);if(status==FG_OK)status=scratch(vk,10240u*tokens,&executor->up_logits,err);if(status==FG_OK)status=scratch(vk,4u*tokens,&executor->inject_logits,err);if(status==FG_OK)status=scratch(vk,2560u*tokens,&executor->mixed,err);if(status==FG_OK)status=scratch(vk,4u*tokens,&executor->injection,err);if(status==FG_OK)status=scratch(vk,10240u*tokens,&executor->hyper_output,err);if(status==FG_OK)status=scratch(vk,10240u*tokens,&executor->hyper_output_b,err);if(status==FG_OK)status=scratch(vk,512u*tokens,&executor->router_logits,err);if(status==FG_OK)status=fg_vk_tensor_create(vk,tokens*FG_Q8K_ACTIVATION_BYTES,&executor->activation_q8k,err);if(status==FG_OK)status=scratch(vk,640u*tokens,&executor->shared_gate,err);if(status==FG_OK)status=scratch(vk,640u*tokens,&executor->shared_up,err);if(status==FG_OK)status=scratch(vk,640u*tokens,&executor->shared_mid,err);if(status==FG_OK)status=scratch(vk,2560u*tokens,&executor->shared_output,err);if(status==FG_OK)status=scratch(vk,tokens,&executor->shared_scalar,err);if(status==FG_OK)status=scratch(vk,2560u*tokens,&executor->reduced,err);if(status==FG_OK)status=scratch(vk,10240u*tokens,&executor->gdn_qkv,err);if(status==FG_OK)status=scratch(vk,10240u*tokens,&executor->gdn_conv_output,err);if(status==FG_OK)status=scratch(vk,6144u*tokens,&executor->gdn_z,err);if(status==FG_OK)status=scratch(vk,48u*tokens,&executor->gdn_alpha,err);if(status==FG_OK)status=scratch(vk,48u*tokens,&executor->gdn_beta,err);if(status==FG_OK)status=scratch(vk,6144u*tokens,&executor->gdn_core,err);if(status==FG_OK)status=scratch(vk,2560u*tokens,&executor->gdn_output,err);
    for(uint32_t layer=0;status==FG_OK&&layer<FG_LAYER_COUNT;layer++){if((layer&3u)!=3u){status=scratch(vk,10240u*4u,&executor->gdn_state[layer].conv_state,err);if(status==FG_OK)status=scratch(vk,48u*128u*128u,&executor->gdn_state[layer].recurrent_state,err);if(status==FG_OK){memset(fg_vk_tensor_map(executor->gdn_state[layer].conv_state),0,10240u*4u*4u);memset(fg_vk_tensor_map(executor->gdn_state[layer].recurrent_state),0,48u*128u*128u*4u);}}}
    if(status==FG_OK){status=scratch(vk,10240u*tokens,&executor->ple_key,err);if(status==FG_OK)status=scratch(vk,2560u*tokens,&executor->ple_value,err);if(status==FG_OK)status=scratch(vk,10240u*tokens,&executor->ple_key_norm,err);if(status==FG_OK)status=scratch(vk,10240u*tokens,&executor->ple_query_norm,err);if(status==FG_OK)status=scratch(vk,10240u*tokens,&executor->ple_gated,err);if(status==FG_OK)status=scratch(vk,10240u*tokens,&executor->ple_gated_norm,err);if(status==FG_OK)status=scratch(vk,10240u*tokens,&executor->ple_output,err);if(status==FG_OK)status=scratch(vk,10240u*tokens,&executor->ple_added,err);if(status==FG_OK)status=scratch(vk,10240u*9u,&executor->ple_state,err);if(status==FG_OK)memset(fg_vk_tensor_map(executor->ple_state),0,10240u*9u*4u);}
    if(status!=FG_OK){fg_owner_executor_destroy(executor);return status;}executor->replicated=true;*out=executor;return FG_OK;
}
void fg_owner_executor_destroy(fg_owner_executor *e){if(!e)return;fg_qsa_session_close(e->qsa);for(uint32_t layer=0;layer<FG_LAYER_COUNT;layer++){fg_vk_tensor_destroy(e->gdn_state[layer].recurrent_state);fg_vk_tensor_destroy(e->gdn_state[layer].conv_state);}fg_vk_tensor_destroy(e->ple_state);fg_vk_tensor_destroy(e->ple_added);fg_vk_tensor_destroy(e->ple_output);fg_vk_tensor_destroy(e->ple_gated_norm);fg_vk_tensor_destroy(e->ple_gated);fg_vk_tensor_destroy(e->ple_query_norm);fg_vk_tensor_destroy(e->ple_key_norm);fg_vk_tensor_destroy(e->ple_value);fg_vk_tensor_destroy(e->ple_key);fg_vk_tensor_destroy(e->gdn_output);fg_vk_tensor_destroy(e->gdn_core);fg_vk_tensor_destroy(e->gdn_beta);fg_vk_tensor_destroy(e->gdn_alpha);fg_vk_tensor_destroy(e->gdn_z);fg_vk_tensor_destroy(e->gdn_conv_output);fg_vk_tensor_destroy(e->gdn_qkv);fg_vk_tensor_destroy(e->reduced);fg_vk_tensor_destroy(e->shared_scalar);fg_vk_tensor_destroy(e->shared_output);fg_vk_tensor_destroy(e->shared_mid);fg_vk_tensor_destroy(e->shared_up);fg_vk_tensor_destroy(e->shared_gate);fg_vk_tensor_destroy(e->activation_q8k);fg_vk_tensor_destroy(e->router_logits);fg_vk_tensor_destroy(e->hyper_output_b);fg_vk_tensor_destroy(e->hyper_output);fg_vk_tensor_destroy(e->injection);fg_vk_tensor_destroy(e->mixed);fg_vk_tensor_destroy(e->inject_logits);fg_vk_tensor_destroy(e->up_logits);fg_vk_tensor_destroy(e->low_active);fg_vk_tensor_destroy(e->low);fg_vk_tensor_destroy(e->hyper_norm);free(e);}

static fg_vk_tensor *weight(fg_owner_executor *executor,uint32_t layer,const char *suffix,fg_error *err){char name[FG_TENSOR_NAME_MAX];int length=snprintf(name,sizeof(name),"blk.%u.%s",layer,suffix);if(length<0||(uint32_t)length>=sizeof(name)){fg_error_set(err,FG_ERR_LIMIT,"owner tensor name overflow");return NULL;}fg_vk_tensor *tensor=fg_model_tensor(executor->model,name);if(!tensor)fg_error_set(err,FG_ERR_MISMATCH,"owner rank is missing %s",name);return tensor;}
static bool owns_layer(const fg_owner_executor *executor,uint32_t layer){if(executor->replicated)return layer<FG_LAYER_COUNT;const fg_manifest *manifest=fg_model_manifest(executor->model);return layer<FG_LAYER_COUNT&&manifest->layer_owner[layer]==fg_model_rank(executor->model);}

fg_status fg_owner_gr_read_batch(fg_owner_executor *e,uint32_t layer,bool ffn,const fg_vk_tensor *hyper_input,uint32_t token_count,fg_vk_tensor **mixed,const fg_vk_tensor **residual,fg_vk_tensor **injection,fg_error *err){
    if(!e||!hyper_input||!mixed||!residual||!injection||!token_count||token_count>e->max_tokens||!owns_layer(e,layer)){fg_error_set(err,FG_ERR_MISMATCH,"gated residual batch is not on the layer owner or exceeds the sealed microbatch");return FG_ERR_MISMATCH;}const char *prefix=ffn?"hc_ffn":"hc_attn";char suffix[48];fg_vk_tensor *norm_weight,*down_weight,*up_weight,*inject_weight;snprintf(suffix,sizeof(suffix),"%s_norm.weight",prefix);norm_weight=weight(e,layer,suffix,err);snprintf(suffix,sizeof(suffix),"%s_down.weight",prefix);down_weight=weight(e,layer,suffix,err);snprintf(suffix,sizeof(suffix),"%s_up.weight",prefix);up_weight=weight(e,layer,suffix,err);snprintf(suffix,sizeof(suffix),"%s_inject.weight",prefix);inject_weight=weight(e,layer,suffix,err);if(!norm_weight||!down_weight||!up_weight||!inject_weight)return FG_ERR_MISMATCH;fg_vk_context *vk=fg_model_vk(e->model);fg_status status=fg_vk_begin(vk,err);if(status==FG_OK)status=fg_vk_group_rms_norm(vk,e->hyper_norm,hyper_input,norm_weight,FG_HIDDEN_SIZE,4u,token_count,1e-6f,err);if(status==FG_OK)status=fg_vk_dense_q8_0_f32(vk,e->low,down_weight,e->hyper_norm,10240u,320u,token_count,1.0f,err);if(status==FG_OK)status=fg_vk_silu_scaled(vk,e->low_active,e->low,token_count*320u,0.25f,err);if(status==FG_OK)status=fg_vk_dense_q8_0_f32(vk,e->up_logits,up_weight,e->low_active,320u,10240u,token_count,1.0f,err);if(status==FG_OK)status=fg_vk_dense_f32(vk,e->inject_logits,inject_weight,e->hyper_norm,10240u,4u,token_count,err);if(status==FG_OK)status=fg_vk_gr_mix(vk,e->mixed,e->injection,e->hyper_norm,e->up_logits,e->inject_logits,FG_HIDDEN_SIZE,4u,token_count,err);if(status==FG_OK){fg_status end_status=fg_vk_end(vk,err);if(end_status!=FG_OK)status=end_status;}if(status==FG_OK){*mixed=e->mixed;*residual=hyper_input;*injection=e->injection;}return status;
}

fg_status fg_owner_gr_read(fg_owner_executor *e,uint32_t layer,bool ffn,const fg_vk_tensor *hyper_input,fg_vk_tensor **mixed,const fg_vk_tensor **residual,fg_vk_tensor **injection,fg_error *err){return fg_owner_gr_read_batch(e,layer,ffn,hyper_input,1u,mixed,residual,injection,err);}

fg_status fg_owner_moe_prepare_batch(fg_owner_executor *e,uint32_t layer,const fg_vk_tensor *hidden,uint16_t token_count,uint16_t *expert_ids,float *gates,const uint8_t **activation,fg_error *err){
    if(!e||!hidden||!token_count||token_count>e->max_tokens||!expert_ids||!gates||!activation||!owns_layer(e,layer)){fg_error_set(err,FG_ERR_MISMATCH,"MoE prepare batch is not on the layer owner or exceeds the sealed microbatch");return FG_ERR_MISMATCH;}fg_vk_tensor *router=weight(e,layer,"ffn_gate_inp.weight",err),*shared_gate_weight=weight(e,layer,"ffn_gate_inp_shexp.weight",err),*gate_weight=weight(e,layer,"ffn_gate_shexp.weight",err),*up_weight=weight(e,layer,"ffn_up_shexp.weight",err),*down_weight=weight(e,layer,"ffn_down_shexp.weight",err);if(!router||!shared_gate_weight||!gate_weight||!up_weight||!down_weight)return FG_ERR_MISMATCH;fg_vk_context *vk=fg_model_vk(e->model);fg_status status=fg_vk_begin(vk,err);if(status==FG_OK)status=fg_vk_dense_f32(vk,e->router_logits,router,hidden,FG_HIDDEN_SIZE,FG_EXPERT_COUNT,token_count,err);if(status==FG_OK){fg_status end_status=fg_vk_end(vk,err);if(end_status!=FG_OK)status=end_status;}if(status!=FG_OK)return status;const float *router_values=fg_vk_tensor_map(e->router_logits);for(uint32_t token=0;status==FG_OK&&token<token_count;token++){uint32_t ids[FG_TOP_K];status=fg_q38_router_topk(router_values+(uint64_t)token*FG_EXPERT_COUNT,FG_EXPERT_COUNT,FG_TOP_K,ids,gates+(uint64_t)token*FG_TOP_K,err);for(uint32_t slot=0;status==FG_OK&&slot<FG_TOP_K;slot++)expert_ids[(uint64_t)token*FG_TOP_K+slot]=(uint16_t)ids[slot];}if(status==FG_OK)status=fg_vk_begin(vk,err);if(status==FG_OK)status=fg_vk_quantize_q8_k(vk,e->activation_q8k,hidden,FG_HIDDEN_SIZE,token_count,err);if(status==FG_OK)status=fg_vk_dense_q8_0_f32(vk,e->shared_gate,gate_weight,hidden,FG_HIDDEN_SIZE,640u,token_count,1.0f,err);if(status==FG_OK)status=fg_vk_dense_q8_0_f32(vk,e->shared_up,up_weight,hidden,FG_HIDDEN_SIZE,640u,token_count,1.0f,err);if(status==FG_OK)status=fg_vk_swiglu(vk,e->shared_mid,e->shared_gate,e->shared_up,(uint32_t)token_count*640u,err);if(status==FG_OK)status=fg_vk_dense_q8_0_f32(vk,e->shared_output,down_weight,e->shared_mid,640u,FG_HIDDEN_SIZE,token_count,1.0f,err);if(status==FG_OK)status=fg_vk_dense_f32(vk,e->shared_scalar,shared_gate_weight,hidden,FG_HIDDEN_SIZE,1u,token_count,err);if(status==FG_OK){fg_status end_status=fg_vk_end(vk,err);if(end_status!=FG_OK)status=end_status;}if(status==FG_OK)*activation=fg_vk_tensor_map(e->activation_q8k);return status;
}

fg_status fg_owner_moe_prepare(fg_owner_executor *e,uint32_t layer,const fg_vk_tensor *hidden,uint16_t expert_ids[FG_TOP_K],float gates[FG_TOP_K],const uint8_t **activation,fg_error *err){return fg_owner_moe_prepare_batch(e,layer,hidden,1u,expert_ids,gates,activation,err);}

fg_status fg_owner_moe_reduce(fg_owner_executor *e,uint32_t layer,uint32_t position,const uint16_t expert_ids[FG_TOP_K],const float gates[FG_TOP_K],const fg_expert_result *results,uint32_t result_count,fg_vk_tensor **output,fg_error *err){
    if(!e||!expert_ids||!gates||!results||!result_count||result_count>FG_GROUP_SIZE||!output){fg_error_set(err,FG_ERR_ARGUMENT,"invalid MoE reduction arguments");return FG_ERR_ARGUMENT;}
    if(!owns_layer(e,layer)){fg_error_set(err,FG_ERR_MISMATCH,"MoE reduction is not on the layer owner");return FG_ERR_MISMATCH;}
    const fg_manifest *manifest=fg_model_manifest(e->model);uint32_t owner=fg_model_rank(e->model);const float *slot_output[FG_TOP_K]={0};bool seen_expert[FG_EXPERT_COUNT]={0};
    for(uint32_t slot=0;slot<FG_TOP_K;slot++){if(expert_ids[slot]>=FG_EXPERT_COUNT||seen_expert[expert_ids[slot]]||!isfinite(gates[slot])){fg_error_set(err,FG_ERR_FORMAT,"invalid canonical route slot %u",slot);return FG_ERR_FORMAT;}seen_expert[expert_ids[slot]]=true;}
    fg_status route_status=fg_expert_results_validate_route(manifest,layer,position,owner,expert_ids,results,result_count,err);if(route_status!=FG_OK)return route_status;
    for(uint32_t r=0;r<result_count;r++)for(uint32_t i=0;i<results[r].selected_count;i++)slot_output[results[r].routing_slots[i]]=results[r].outputs[i];
    for(uint32_t slot=0;slot<FG_TOP_K;slot++){
        if(!slot_output[slot]){fg_error_set(err,FG_ERR_MISMATCH,"missing expert result slot %u",slot);return FG_ERR_MISMATCH;}
    }
    float shared_scale=1.0f/(1.0f+expf(-*(const float *)fg_vk_tensor_map(e->shared_scalar)));
    /* Cache-friendly reduction: copy GPU-mapped (write-combining) data to stack,
       reduce in L1, then write result back.  The WC mapping makes scattered reads
       ~20x slower than cached DRAM; this copy+reduce pattern eliminates that. */
    float shared_local[FG_HIDDEN_SIZE],result_local[FG_HIDDEN_SIZE];
    memcpy(shared_local,fg_vk_tensor_map(e->shared_output),FG_HIDDEN_SIZE*sizeof(float));
    for(uint32_t element=0;element<FG_HIDDEN_SIZE;element++)result_local[element]=shared_scale*shared_local[element];
    for(uint32_t slot=0;slot<FG_TOP_K;slot++){float g=gates[slot];const float *out=slot_output[slot];for(uint32_t element=0;element<FG_HIDDEN_SIZE;element++)result_local[element]=fmaf(g,out[element],result_local[element]);}
    memcpy(fg_vk_tensor_map(e->reduced),result_local,FG_HIDDEN_SIZE*sizeof(float));
    *output=e->reduced;return FG_OK;
}

fg_status fg_owner_moe_reduce_batch(fg_owner_executor *e,uint32_t layer,uint32_t first_position,uint16_t token_count,const uint16_t *expert_ids,const float *gates,const fg_prefill_result *results,uint32_t result_count,fg_vk_tensor **output,fg_error *err){
    if(!e||!token_count||token_count>e->max_tokens||!expert_ids||!gates||!results||!result_count||result_count>FG_GROUP_SIZE||!output||!owns_layer(e,layer)){fg_error_set(err,FG_ERR_ARGUMENT,"invalid owner MoE batch reduction arguments");return FG_ERR_ARGUMENT;}fg_status status=fg_prefill_results_validate_route(fg_model_manifest(e->model),layer,first_position,fg_model_rank(e->model),token_count,expert_ids,results,result_count,err);if(status!=FG_OK)return status;
    const float **slot_outputs=calloc((size_t)token_count*FG_TOP_K,sizeof(*slot_outputs));if(!slot_outputs){fg_error_set(err,FG_ERR_OOM,"allocate canonical prefill reduction slots");return FG_ERR_OOM;}for(uint32_t result_index=0;result_index<result_count;result_index++)for(uint32_t pair=0;pair<results[result_index].pair_count;pair++){uint32_t token=results[result_index].pairs[pair].token_slot,slot=results[result_index].pairs[pair].routing_slot;slot_outputs[(uint64_t)token*FG_TOP_K+slot]=results[result_index].outputs+(uint64_t)pair*FG_HIDDEN_SIZE;}
    const float *shared=fg_vk_tensor_map(e->shared_output),*shared_scalar=fg_vk_tensor_map(e->shared_scalar);float *reduced=fg_vk_tensor_map(e->reduced);for(uint32_t token=0;token<token_count;token++){float shared_scale=1.0f/(1.0f+expf(-shared_scalar[token]));for(uint32_t element=0;element<FG_HIDDEN_SIZE;element++){float value=shared_scale*shared[(uint64_t)token*FG_HIDDEN_SIZE+element];for(uint32_t slot=0;slot<FG_TOP_K;slot++){const float *expert=slot_outputs[(uint64_t)token*FG_TOP_K+slot];float gate=gates[(uint64_t)token*FG_TOP_K+slot];if(!expert||!isfinite(gate)){free(slot_outputs);fg_error_set(err,FG_ERR_MISMATCH,"missing or invalid canonical prefill reduction slot");return FG_ERR_MISMATCH;}value=fmaf(gate,expert[element],value);}reduced[(uint64_t)token*FG_HIDDEN_SIZE+element]=value;}}
    free(slot_outputs);*output=e->reduced;return FG_OK;
}

fg_status fg_owner_gr_write_batch(fg_owner_executor *executor,const fg_vk_tensor *hyper_input,const fg_vk_tensor *block_output,const fg_vk_tensor *injection,uint32_t token_count,fg_vk_tensor **output,fg_error *err){if(!executor||!hyper_input||!block_output||!injection||!token_count||token_count>executor->max_tokens||!output){fg_error_set(err,FG_ERR_ARGUMENT,"invalid gated residual batch write arguments");return FG_ERR_ARGUMENT;}fg_vk_tensor *dst=hyper_input!=executor->hyper_output?executor->hyper_output:executor->hyper_output_b;fg_status status=fg_vk_gr_write(fg_model_vk(executor->model),dst,hyper_input,block_output,injection,FG_HIDDEN_SIZE,4u,token_count,err);if(status==FG_OK)*output=dst;return status;}

fg_status fg_owner_gr_write(fg_owner_executor *executor,const fg_vk_tensor *hyper_input,const fg_vk_tensor *block_output,const fg_vk_tensor *injection,fg_vk_tensor **output,fg_error *err){return fg_owner_gr_write_batch(executor,hyper_input,block_output,injection,1u,output,err);}

fg_status fg_owner_gdn_decode(fg_owner_executor *executor,uint32_t layer,const fg_vk_tensor *hidden,fg_vk_tensor **output,fg_error *err){
    if(!executor||!hidden||!output||!owns_layer(executor,layer)||(layer&3u)==3u||!executor->gdn_state[layer].conv_state||!executor->gdn_state[layer].recurrent_state){fg_error_set(err,FG_ERR_MISMATCH,"GDN decode is not on an owned linear-attention layer");return FG_ERR_MISMATCH;}
    fg_vk_tensor *qkv_weight=weight(executor,layer,"attn_qkv.weight",err),*z_weight=weight(executor,layer,"attn_gate.weight",err),*alpha_weight=weight(executor,layer,"ssm_alpha.weight",err),*beta_weight=weight(executor,layer,"ssm_beta.weight",err),*conv_weight=weight(executor,layer,"ssm_conv1d.weight",err),*a_decay=weight(executor,layer,"ssm_a",err),*dt_bias=weight(executor,layer,"ssm_dt.bias",err),*norm_weight=weight(executor,layer,"ssm_norm.weight",err),*out_weight=weight(executor,layer,"ssm_out.weight",err);if(!qkv_weight||!z_weight||!alpha_weight||!beta_weight||!conv_weight||!a_decay||!dt_bias||!norm_weight||!out_weight)return FG_ERR_MISMATCH;
    fg_vk_context *vk=fg_model_vk(executor->model);
    static atomic_int gdn_diag_done=0;
    if(!gdn_diag_done){gdn_diag_done=1;const float *a_vals=fg_vk_tensor_map(a_decay),*dt_vals=fg_vk_tensor_map(dt_bias);fprintf(stderr,"GDN_DIAG layer=%u ssm_a[0..7]=%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f dt_bias[0..3]=%.4f,%.4f,%.4f,%.4f\n",layer,a_vals[0],a_vals[1],a_vals[2],a_vals[3],a_vals[4],a_vals[5],a_vals[6],a_vals[7],dt_vals[0],dt_vals[1],dt_vals[2],dt_vals[3]);}
    fg_status status=fg_vk_begin(vk,err);if(status==FG_OK)status=fg_vk_dense_q8_0_f32(vk,executor->gdn_qkv,qkv_weight,hidden,2560u,10240u,1u,1.0f,err);if(status==FG_OK)status=fg_vk_dense_q8_0_f32(vk,executor->gdn_z,z_weight,hidden,2560u,6144u,1u,1.0f,err);if(status==FG_OK)status=fg_vk_dense_f32(vk,executor->gdn_alpha,alpha_weight,hidden,2560u,48u,1u,err);if(status==FG_OK)status=fg_vk_dense_f32(vk,executor->gdn_beta,beta_weight,hidden,2560u,48u,1u,err);if(status==FG_OK)status=fg_vk_gdn_conv_decode(vk,executor->gdn_conv_output,executor->gdn_state[layer].conv_state,executor->gdn_qkv,conv_weight,10240u,err);if(status==FG_OK)status=fg_vk_gdn_recurrent_decode(vk,executor->gdn_core,executor->gdn_state[layer].recurrent_state,executor->gdn_conv_output,executor->gdn_z,executor->gdn_alpha,executor->gdn_beta,a_decay,dt_bias,norm_weight,48u,16u,128u,1e-6f,err);if(status==FG_OK){fg_status end_status=fg_vk_end(vk,err);if(end_status!=FG_OK)status=end_status;}
    if(status==FG_OK&&layer==0u){const float *alpha_vals=fg_vk_tensor_map(executor->gdn_alpha),*a_vals2=fg_vk_tensor_map(a_decay),*dt_vals2=fg_vk_tensor_map(dt_bias);float sp0=alpha_vals[0]+dt_vals2[0];sp0=sp0>0.0f?sp0+logf(1.0f+expf(-sp0)):logf(1.0f+expf(sp0));float example_decay=expf(a_vals2[0]*sp0);fprintf(stderr,"GDN_DECAY layer=0 alpha[0]=%.4f softplus=%.4f a[0]=%.4f decay[0]=%.6f\n",alpha_vals[0],sp0,a_vals2[0],example_decay);}
    if(status==FG_OK){status=fg_vk_begin(vk,err);if(status==FG_OK)status=fg_vk_dense_q8_0_f32(vk,executor->gdn_output,out_weight,executor->gdn_core,6144u,2560u,1u,1.0f,err);if(status==FG_OK){fg_status end_status=fg_vk_end(vk,err);if(end_status!=FG_OK)status=end_status;}}if(status==FG_OK){*output=executor->gdn_output;}return status;
}

fg_status fg_owner_gdn_prefill(fg_owner_executor *executor,uint32_t layer,uint32_t token_count,const fg_vk_tensor *hidden,fg_vk_tensor **output,fg_error *err){
    if(!executor||!hidden||!output||!token_count||token_count>executor->max_tokens||!owns_layer(executor,layer)||(layer&3u)==3u||!executor->gdn_state[layer].conv_state||!executor->gdn_state[layer].recurrent_state){fg_error_set(err,FG_ERR_MISMATCH,"GDN prefill is not on an owned linear-attention layer or exceeds the sealed microbatch");return FG_ERR_MISMATCH;}fg_vk_tensor *qkv_weight=weight(executor,layer,"attn_qkv.weight",err),*z_weight=weight(executor,layer,"attn_gate.weight",err),*alpha_weight=weight(executor,layer,"ssm_alpha.weight",err),*beta_weight=weight(executor,layer,"ssm_beta.weight",err),*conv_weight=weight(executor,layer,"ssm_conv1d.weight",err),*a_decay=weight(executor,layer,"ssm_a",err),*dt_bias=weight(executor,layer,"ssm_dt.bias",err),*norm_weight=weight(executor,layer,"ssm_norm.weight",err),*out_weight=weight(executor,layer,"ssm_out.weight",err);if(!qkv_weight||!z_weight||!alpha_weight||!beta_weight||!conv_weight||!a_decay||!dt_bias||!norm_weight||!out_weight)return FG_ERR_MISMATCH;
    fg_vk_context *vk=fg_model_vk(executor->model);fg_status status=fg_vk_begin(vk,err);if(status==FG_OK)status=fg_vk_dense_q8_0_f32(vk,executor->gdn_qkv,qkv_weight,hidden,2560u,10240u,token_count,1.0f,err);if(status==FG_OK)status=fg_vk_dense_q8_0_f32(vk,executor->gdn_z,z_weight,hidden,2560u,6144u,token_count,1.0f,err);if(status==FG_OK)status=fg_vk_dense_f32(vk,executor->gdn_alpha,alpha_weight,hidden,2560u,48u,token_count,err);if(status==FG_OK)status=fg_vk_dense_f32(vk,executor->gdn_beta,beta_weight,hidden,2560u,48u,token_count,err);if(status==FG_OK)status=fg_vk_gdn_conv_prefill(vk,executor->gdn_conv_output,executor->gdn_state[layer].conv_state,executor->gdn_qkv,conv_weight,10240u,token_count,err);if(status==FG_OK)status=fg_vk_gdn_recurrent_prefill(vk,executor->gdn_core,executor->gdn_state[layer].recurrent_state,executor->gdn_conv_output,executor->gdn_z,executor->gdn_alpha,executor->gdn_beta,a_decay,dt_bias,norm_weight,48u,16u,128u,token_count,1e-6f,err);if(status==FG_OK)status=fg_vk_dense_q8_0_f32(vk,executor->gdn_output,out_weight,executor->gdn_core,6144u,2560u,token_count,1.0f,err);if(status==FG_OK){fg_status end_status=fg_vk_end(vk,err);if(end_status!=FG_OK)status=end_status;}if(status==FG_OK)*output=executor->gdn_output;return status;
}

fg_status fg_owner_ple_decode(fg_owner_executor *e,const fg_vk_tensor *hyper,const fg_vk_tensor *embedding,fg_vk_tensor **output,fg_error *err){
    if(!e||!hyper||!embedding||!output||!owns_layer(e,1u)||!e->ple_state){fg_error_set(err,FG_ERR_MISMATCH,"PLE decode is not on the layer-1 owner");return FG_ERR_MISMATCH;}fg_vk_tensor *key_weight=weight(e,1u,"ple_key.weight",err),*value_weight=weight(e,1u,"ple_value.weight",err),*key_norm=weight(e,1u,"ple_norm_key.weight",err),*query_norm=weight(e,1u,"ple_norm_query.weight",err),*conv_norm=weight(e,1u,"ple_norm_conv.weight",err),*conv_weight=weight(e,1u,"ple_conv1d.weight",err);if(!key_weight||!value_weight||!key_norm||!query_norm||!conv_norm||!conv_weight)return FG_ERR_MISMATCH;fg_vk_context *vk=fg_model_vk(e->model);fg_status status=fg_vk_begin(vk,err);if(status==FG_OK)status=fg_vk_dense_q8_0_f32(vk,e->ple_key,key_weight,embedding,2560u,10240u,1u,1.0f,err);if(status==FG_OK)status=fg_vk_dense_q8_0_f32(vk,e->ple_value,value_weight,embedding,2560u,2560u,1u,1.0f,err);if(status==FG_OK)status=fg_vk_group_rms_norm(vk,e->ple_key_norm,e->ple_key,key_norm,2560u,4u,1u,1e-6f,err);if(status==FG_OK)status=fg_vk_group_rms_norm(vk,e->ple_query_norm,hyper,query_norm,2560u,4u,1u,1e-6f,err);if(status==FG_OK)status=fg_vk_ple_gate(vk,e->ple_gated,e->ple_key_norm,e->ple_query_norm,e->ple_value,err);if(status==FG_OK)status=fg_vk_group_rms_norm(vk,e->ple_gated_norm,e->ple_gated,conv_norm,2560u,4u,1u,1e-6f,err);if(status==FG_OK)status=fg_vk_ple_conv_decode(vk,e->ple_output,e->ple_state,e->ple_gated,e->ple_gated_norm,conv_weight,err);if(status==FG_OK)status=fg_vk_add_f32(vk,e->ple_added,hyper,e->ple_output,10240u,err);if(status==FG_OK){fg_status end_status=fg_vk_end(vk,err);if(end_status!=FG_OK)status=end_status;}if(status==FG_OK)*output=e->ple_added;return status;
}

fg_status fg_owner_ple_prefill(fg_owner_executor *e,const fg_vk_tensor *hyper,const fg_vk_tensor *embedding,uint32_t token_count,fg_vk_tensor **output,fg_error *err){
    if(!e||!hyper||!embedding||!output||!token_count||token_count>e->max_tokens||fg_model_manifest(e->model)->layer_owner[1u]!=fg_model_rank(e->model)||!e->ple_state){fg_error_set(err,FG_ERR_MISMATCH,"PLE prefill is not on the layer-1 owner or exceeds the sealed microbatch");return FG_ERR_MISMATCH;}fg_vk_tensor *key_weight=weight(e,1u,"ple_key.weight",err),*value_weight=weight(e,1u,"ple_value.weight",err),*key_norm=weight(e,1u,"ple_norm_key.weight",err),*query_norm=weight(e,1u,"ple_norm_query.weight",err),*conv_norm=weight(e,1u,"ple_norm_conv.weight",err),*conv_weight=weight(e,1u,"ple_conv1d.weight",err);if(!key_weight||!value_weight||!key_norm||!query_norm||!conv_norm||!conv_weight)return FG_ERR_MISMATCH;fg_vk_context *vk=fg_model_vk(e->model);fg_status status=fg_vk_begin(vk,err);if(status==FG_OK)status=fg_vk_dense_q8_0_f32(vk,e->ple_key,key_weight,embedding,2560u,10240u,token_count,1.0f,err);if(status==FG_OK)status=fg_vk_dense_q8_0_f32(vk,e->ple_value,value_weight,embedding,2560u,2560u,token_count,1.0f,err);if(status==FG_OK)status=fg_vk_group_rms_norm(vk,e->ple_key_norm,e->ple_key,key_norm,2560u,4u,token_count,1e-6f,err);if(status==FG_OK)status=fg_vk_group_rms_norm(vk,e->ple_query_norm,hyper,query_norm,2560u,4u,token_count,1e-6f,err);if(status==FG_OK)status=fg_vk_ple_gate_prefill(vk,e->ple_gated,e->ple_key_norm,e->ple_query_norm,e->ple_value,token_count,err);if(status==FG_OK)status=fg_vk_group_rms_norm(vk,e->ple_gated_norm,e->ple_gated,conv_norm,2560u,4u,token_count,1e-6f,err);if(status==FG_OK)status=fg_vk_ple_conv_prefill(vk,e->ple_output,e->ple_state,e->ple_gated,e->ple_gated_norm,conv_weight,token_count,err);if(status==FG_OK)status=fg_vk_add_f32(vk,e->ple_added,hyper,e->ple_output,token_count*10240u,err);if(status==FG_OK){fg_status end_status=fg_vk_end(vk,err);if(end_status!=FG_OK)status=end_status;}if(status==FG_OK)*output=e->ple_added;return status;
}

fg_status fg_owner_qsa_open(fg_owner_executor *executor,const char *state_path,bool create,fg_error *err){
    if(!executor||!state_path){fg_error_set(err,FG_ERR_ARGUMENT,"invalid owner QSA open arguments");return FG_ERR_ARGUMENT;}
    if(executor->qsa){fg_error_set(err,FG_ERR_MISMATCH,"owner QSA session is already open");return FG_ERR_MISMATCH;}
    return fg_qsa_session_open(&executor->qsa,executor->model,state_path,create,err);
}
fg_status fg_owner_qsa_open_decode(fg_owner_executor *executor,const char *state_path,uint32_t resident_tokens,fg_error *err){
    if(!executor||!state_path){fg_error_set(err,FG_ERR_ARGUMENT,"invalid owner QSA decode open arguments");return FG_ERR_ARGUMENT;}
    if(executor->qsa){fg_error_set(err,FG_ERR_MISMATCH,"owner QSA session is already open");return FG_ERR_MISMATCH;}
    return fg_qsa_session_open_decode(&executor->qsa,executor->model,state_path,resident_tokens,err);
}
void fg_owner_qsa_set_tokens(fg_owner_executor *executor,uint32_t tokens){if(executor&&executor->qsa)fg_qsa_session_set_tokens(executor->qsa,tokens);}

fg_status fg_owner_qsa_decode(fg_owner_executor *executor,uint32_t layer,uint32_t token,const uint32_t position[3],const fg_vk_tensor *hidden,fg_vk_tensor **output,fg_error *err){
    if(!executor||!executor->qsa||!owns_layer(executor,layer)||(layer&3u)!=3u){fg_error_set(err,FG_ERR_MISMATCH,"QSA decode is not on an initialized QSA layer owner");return FG_ERR_MISMATCH;}
    return fg_qsa_session_decode(executor->qsa,layer,token,position,hidden,output,err);
}

fg_status fg_owner_qsa_prefill(fg_owner_executor *executor,uint32_t layer,uint32_t first_token,const uint32_t *positions,uint32_t token_count,const fg_vk_tensor *hidden,fg_vk_tensor **output,fg_error *err){
    if(!executor||!executor->qsa||!owns_layer(executor,layer)||(layer&3u)!=3u||!token_count||token_count>executor->max_tokens){fg_error_set(err,FG_ERR_MISMATCH,"QSA prefill is not on an initialized QSA layer owner or exceeds the sealed microbatch");return FG_ERR_MISMATCH;}
    return fg_qsa_session_prefill(executor->qsa,layer,first_token,positions,token_count,hidden,output,err);
}

static float tensor_l2(const fg_vk_tensor *t,uint32_t n){const float *p=fg_vk_tensor_map((fg_vk_tensor *)t);if(!p)return -1.0f;double s=0.0;for(uint32_t i=0;i<n;i++)s+=(double)p[i]*p[i];return (float)sqrt(s/n);}

fg_status fg_owner_decode_layer(fg_owner_executor *e,uint32_t layer,uint32_t token,const uint32_t position[3],const fg_vk_tensor *hyper_input,const fg_vk_tensor *ngram_embedding,fg_owner_expert_dispatch_fn dispatch,void *dispatch_context,fg_vk_tensor **output,fg_error *err){
    if(!e||!position||!hyper_input||!dispatch||!output||!owns_layer(e,layer)){fg_error_set(err,FG_ERR_MISMATCH,"text layer decode is not on its owner");return FG_ERR_MISMATCH;}if((layer==1u)!=(ngram_embedding!=NULL)){fg_error_set(err,FG_ERR_MISMATCH,"layer-1 PLE embedding presence mismatch");return FG_ERR_MISMATCH;}double t0=ts_ms();const fg_vk_tensor *layer_input=hyper_input;if(layer==1u){fg_vk_tensor *ple_input=NULL;fg_status status=fg_owner_ple_decode(e,hyper_input,ngram_embedding,&ple_input,err);if(status!=FG_OK)return status;layer_input=ple_input;}double t_ple=ts_ms();
    int diag=token<30u; /* first ~11 decode tokens */
    fg_vk_context *vk=fg_model_vk(e->model);
    /* ---- FUSED BATCH 1: gr_read(attn) + attention + gr_write + gr_read(FFN) + router ---- */
    fg_vk_tensor *mixed=NULL,*injection=NULL,*block=NULL,*after_attention=NULL;const fg_vk_tensor *residual=NULL;
    fg_status status=fg_vk_begin(vk,err);if(status==FG_OK){status=fg_owner_gr_read(e,layer,false,layer_input,&mixed,&residual,&injection,err);}double t_gr1=ts_ms();
    if(status==FG_OK){status=(layer&3u)==3u?fg_owner_qsa_decode(e,layer,token,position,mixed,&block,err):fg_owner_gdn_decode(e,layer,mixed,&block,err);}double t_attn=ts_ms();
    if(status==FG_OK){status=fg_owner_gr_write(e,residual,block,injection,&after_attention,err);}double t_grw1=ts_ms();
    if(status==FG_OK){status=fg_owner_gr_read(e,layer,true,after_attention,&mixed,&residual,&injection,err);}double t_gr2=ts_ms();
    /* router matmul — stays in the same fused batch */
    fg_vk_tensor *router_w=status==FG_OK?weight(e,layer,"ffn_gate_inp.weight",err):NULL;
    if(status==FG_OK&&!router_w)status=FG_ERR_MISMATCH;
    if(status==FG_OK)status=fg_vk_dense_f32(vk,e->router_logits,router_w,mixed,FG_HIDDEN_SIZE,FG_EXPERT_COUNT,1u,err);
    if(status==FG_OK){fg_status es=fg_vk_end(vk,err);if(es!=FG_OK)status=es;} /* SYNC 1: read router logits for CPU top-K */
    else if(fg_vk_batch_active(vk))fg_vk_end(vk,err); /* clean up batch on error path */
    double t_router=ts_ms();
    /* CPU top-K routing */
    uint16_t expert_ids[FG_TOP_K];float gates[FG_TOP_K];const uint8_t *activation=NULL;
    if(status==FG_OK){const float *rv=fg_vk_tensor_map(e->router_logits);uint32_t ids[FG_TOP_K];status=fg_q38_router_topk(rv,FG_EXPERT_COUNT,FG_TOP_K,ids,gates,err);for(uint32_t s=0;status==FG_OK&&s<FG_TOP_K;s++)expert_ids[s]=(uint16_t)ids[s];}
    /* ---- FUSED BATCH 2: quantize + shared expert ---- */
    fg_vk_tensor *shared_gate_w=NULL,*gate_w=NULL,*up_w=NULL,*down_w=NULL;
    if(status==FG_OK){shared_gate_w=weight(e,layer,"ffn_gate_inp_shexp.weight",err);gate_w=weight(e,layer,"ffn_gate_shexp.weight",err);up_w=weight(e,layer,"ffn_up_shexp.weight",err);down_w=weight(e,layer,"ffn_down_shexp.weight",err);if(!shared_gate_w||!gate_w||!up_w||!down_w)status=FG_ERR_MISMATCH;}
    if(status==FG_OK)status=fg_vk_begin(vk,err);
    if(status==FG_OK)status=fg_vk_quantize_q8_k(vk,e->activation_q8k,mixed,FG_HIDDEN_SIZE,1u,err);
    if(status==FG_OK)status=fg_vk_dense_q8_0_f32(vk,e->shared_gate,gate_w,mixed,FG_HIDDEN_SIZE,640u,1u,1.0f,err);
    if(status==FG_OK)status=fg_vk_dense_q8_0_f32(vk,e->shared_up,up_w,mixed,FG_HIDDEN_SIZE,640u,1u,1.0f,err);
    if(status==FG_OK)status=fg_vk_swiglu(vk,e->shared_mid,e->shared_gate,e->shared_up,640u,err);
    if(status==FG_OK)status=fg_vk_dense_q8_0_f32(vk,e->shared_output,down_w,e->shared_mid,640u,FG_HIDDEN_SIZE,1u,1.0f,err);
    if(status==FG_OK)status=fg_vk_dense_f32(vk,e->shared_scalar,shared_gate_w,mixed,FG_HIDDEN_SIZE,1u,1u,err);
    if(status==FG_OK){fg_status es=fg_vk_end(vk,err);if(es!=FG_OK)status=es;} /* SYNC 2: read activation + shared output */
    else if(fg_vk_batch_active(vk))fg_vk_end(vk,err);
    if(status==FG_OK)activation=fg_vk_tensor_map(e->activation_q8k);
    double t_mprep=ts_ms();
    /* expert dispatch + reduce + final gr_write (unchanged) */
    fg_expert_result results[FG_GROUP_SIZE];uint32_t result_count=0;if(status==FG_OK)status=dispatch(dispatch_context,layer,token,expert_ids,gates,activation,results,&result_count,err);double t_exp=ts_ms();if(status==FG_OK)status=fg_owner_moe_reduce(e,layer,token,expert_ids,gates,results,result_count,&block,err);double t_red=ts_ms();if(status==FG_OK)status=fg_owner_gr_write(e,residual,block,injection,output,err);double t_end=ts_ms();
    float attn_block_l2=diag&&status==FG_OK?tensor_l2(block,FG_HIDDEN_SIZE):0.0f;
    if(diag&&status==FG_OK){fprintf(stderr,"layer[%u] t=%u in=%.4f attn_blk=%.4f attn=%.4f moe=%.4f out=%.4f exp=%u,%u,%u",layer,token,tensor_l2(layer_input,FG_HYPER_WIDTH),attn_block_l2,tensor_l2(after_attention,FG_HYPER_WIDTH),tensor_l2(block,FG_HIDDEN_SIZE),tensor_l2(*output,FG_HYPER_WIDTH),expert_ids[0],expert_ids[1],expert_ids[2]);if(layer==0u&&(layer&3u)!=3u)fprintf(stderr," gdn_state=%.6f",tensor_l2(e->gdn_state[layer].recurrent_state,48u*128u*128u));fprintf(stderr,"\n");}
    if(token>=26u&&token<32u){fprintf(stderr,"TIMING layer[%u] t=%u total=%.1f ple=%.1f gr_read=%.1f attn=%.1f gr_write=%.1f gr_read2=%.1f router=%.1f moe_prep=%.1f expert=%.1f moe_red=%.1f gr_write2=%.1f\n",layer,token,t_end-t0,t_ple-t0,t_gr1-t_ple,t_attn-t_gr1,t_grw1-t_attn,t_gr2-t_grw1,t_router-t_gr2,t_mprep-t_router,t_exp-t_mprep,t_red-t_exp,t_end-t_red);}
    return status;
}

fg_status fg_owner_prefill_layer(fg_owner_executor *e,uint32_t layer,uint32_t first_token,const uint32_t *positions,uint16_t token_count,const fg_vk_tensor *hyper_input,const fg_vk_tensor *ngram_embeddings,fg_owner_prefill_dispatch_fn dispatch,void *dispatch_context,fg_vk_tensor **output,fg_error *err){
    if(!e||!positions||!token_count||token_count>e->max_tokens||!hyper_input||!dispatch||!output||!owns_layer(e,layer)){fg_error_set(err,FG_ERR_MISMATCH,"text layer prefill is not on its owner or exceeds the sealed microbatch");return FG_ERR_MISMATCH;}if((layer==1u)!=(ngram_embeddings!=NULL)){fg_error_set(err,FG_ERR_MISMATCH,"layer-1 batched PLE embedding presence mismatch");return FG_ERR_MISMATCH;}const fg_vk_tensor *layer_input=hyper_input;if(layer==1u){fg_vk_tensor *ple_input=NULL;fg_status status=fg_owner_ple_prefill(e,hyper_input,ngram_embeddings,token_count,&ple_input,err);if(status!=FG_OK)return status;layer_input=ple_input;}
    fg_vk_tensor *mixed=NULL,*injection=NULL,*block=NULL,*after_attention=NULL;const fg_vk_tensor *residual=NULL;fg_status status=fg_owner_gr_read_batch(e,layer,false,layer_input,token_count,&mixed,&residual,&injection,err);if(status==FG_OK)status=(layer&3u)==3u?fg_owner_qsa_prefill(e,layer,first_token,positions,token_count,mixed,&block,err):fg_owner_gdn_prefill(e,layer,token_count,mixed,&block,err);if(status==FG_OK)status=fg_owner_gr_write_batch(e,residual,block,injection,token_count,&after_attention,err);if(status!=FG_OK)return status;
    status=fg_owner_gr_read_batch(e,layer,true,after_attention,token_count,&mixed,&residual,&injection,err);uint16_t expert_ids[FG_PREFILL_MAX_PAIRS];float gates[FG_PREFILL_MAX_PAIRS];const uint8_t *activations=NULL;if(status==FG_OK)status=fg_owner_moe_prepare_batch(e,layer,mixed,token_count,expert_ids,gates,&activations,err);fg_prefill_result results[FG_GROUP_SIZE]={0};uint32_t result_count=0;if(status==FG_OK)status=dispatch(dispatch_context,layer,first_token,token_count,expert_ids,gates,activations,results,&result_count,err);if(status==FG_OK)status=fg_owner_moe_reduce_batch(e,layer,first_token,token_count,expert_ids,gates,results,result_count,&block,err);if(status==FG_OK)status=fg_owner_gr_write_batch(e,residual,block,injection,token_count,output,err);return status;
}
